### ISSUE TITLE
Set-cookie on two different database replications and session expiry.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#737] opened 2015-09-11 23:12 UTC
Hi Folks,

http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/administering-sync-gateway/authenticating-users/index.html#custom--indirect--authentication

http://developer.couchbase.com/documentation/mobile/1.1.0/develop/guides/couchbase-lite/native-api/replication/index.html

Design:
Android Client side:
2 Databases and corresponding push and pull replications started and set cookie is set.
2 databases have different sessions.

Server:
Custom Digest auth is followed and 2 cookies for two different database are sent to client. Cookie names remain same i,e SyncGatewaySession but values are different.

Problem:
After
1)Replications of DB1 is created,set cookie set and started.
2)Replications of DB2 is created,set cookie set and started.

The only DB2 replication is sending cookie to to server not the DB1 replication.Hence 401 for DB1 replication.

To be precise only cookie which is set last is hold by httpcookiefactory.

Is the cookie same name the issue here? can we get the custom cookie name from Syncgateway?
Need more insight on the design and the usage/generation for cookie.

Session expiry:
Current version of CBL replicator does not automatically update session. With current design, this is client application's responsibility. When the replicator encounters 401 issue, 1) stop replicator, 2) retrieve new session id from an authentication server, 3) set new session id into the replicator, 4) restart replicator.
This the only way to check session expiry? what are steps taken to below issue?
https://github.com/couchbase/couchbase-lite-java-core/issues/576

Thanks
Nithin

**Comment by zgramana** [comment] 2015-09-18 22:45
Duplicate of #694.

**Closed** 2015-09-18 22:45 UTC
Labels: testneeded
