### ISSUE TITLE
CBL Android 1.3 doesn't work with SGW 1.1

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#1414] opened 2016-08-29 15:34 UTC
From https://github.com/couchbase/couchbase-lite-android/issues/956.

After upgrade cbl to 1.3, the sync with sync gateway 1.1.1 does not work anymore:

W/Sync: com.couchbase.lite.replicator.ReplicationInternal$11@d0663d8: error getting remote checkpoint com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:265) at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165) at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) at java.util.concurrent.FutureTask.run(FutureTask.java:237) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:833) W/Sync: PullerInternal{unknown, pull, 217bd}: Progress: set error = com.couchbase.lite.replicator.RemoteRequestResponseException: Unauthorized W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {GET, http://<ip>/sg/<db>/_local/217bd8467805910e24b487a3e7e900a9aa8e2bf4}: aborting request: okhttp3.RealCall@f348331 I/chromium: [INFO:CONSOLE(8)] "sync response: [{"session_id":"repl013"},{"session_id":"repl014"}]", source: file:///android_asset/www/app.js (8)

**Comment by pasin** [comment] 2016-08-29 21:27
From the exception, it seems like there is an issue with authentication. I'm closing the issue now until there is more info.

**Comment by HanzhiDou** [comment] 2016-08-30 00:39
But if I changed back to CBL 1.2.1, sync works fine, no any code changes, i guess there might be something need to be changed.

**Comment by pasin** [comment] 2016-08-30 01:24
@HanzhiDou how do you setup the session cookie to the replicator? Would it be possible to show the code snippet?

**Comment by pasin** [comment] 2016-08-30 03:19
Copied from couchbase/couchbase-lite-android#956

@pasin  some related code:

Pull Replication:
````
pullReplicate: function (remoteDb, localDb, continuous, channels) {
        var channels = channels || ['*'];
        var continuous = continuous || false;
        var source = {
            headers: {
                Cookie: this.getSyncCredential(remoteDb).cookie_name + '=' + this.getSyncCredential(remoteDb).session_id
            },
            url: this.getSyncGatewayBaseUrl() + remoteDb
        };
        return this.replicate(source, localDb, remoteDb, continuous, false, channels);
    }
````
Push Replication:
```
pushReplicate: function (remoteDb, localDb, continuous, pushFilter) {
        var continuous = continuous || false;
        var target = {
            headers: {
                Cookie: this.getSyncCredential(remoteDb).cookie_name + '=' + this.getSyncCredential(remoteDb).session_id
            },
            url: this.getSyncGatewayBaseUrl() + remoteDb
        };
        return this.replicate(localDb, target, remoteDb, continuous, false, null, pushFilter);
    }
```

sync request:
````
replicate: function (source, target, remoteDb, continuous, cancel, channels, pushFilter) {
   var requestData = {
            continuous: continuous,
            source: source,
            target: target,
            create_target: false
        };
        if (cancel) {
            requestData.cancel = true;
        }
        if (channels) {
            requestData.filter = 'sync_gateway/bychannel';
            requestData.query_params = {
                "channels": channels.join(',')
            };
        }
        if (pushFilter) {
            requestData.filter = pushFilter.filter;
            requestData.query_params = pushFilter.query_params;
        }
        document.cookie = me.getSyncCredential(remoteDb).cookie_name + ':' + me.getSyncCredential(remoteDb).session_id;

        ajaxRequest({
            url: window.cbliteUrl + '_replicate',
            method: 'POST',
            xhr2: false,
            disableCaching: false,
            withCredentials: true,
            useDefaultXhrHeader: false,
            jsonData: requestData,
            headers: {//                Cookie: me.getSyncCredential(remoteDb).cookie_name + '=' + me.getSyncCredential(remoteDb).session_id
            },
            timeout: 30000,
            success: function (response) {
            },
            failure: function (response) {
            }
        });
}
````

Due to one error on android, I changed the code to use document.cookie instead of Cookie header on Android.

**Comment by pasin** [comment] 2016-08-30 03:33
I don't see anything wrong from the code above. I believe setting document.cookie is unnecessary as _replicate request itself doesn't use or verify the cookie.

**Comment by pasin** [comment] 2016-08-30 03:39
@HanzhiDou Can you help verifying the following?

1. Print out `this.getSyncCredential(remoteDb).cookie_name + '=' + this.getSyncCredential(remoteDb).session_id` value when calling pullReplicate or pushReplicate.

2. Verify if the session is still valid by using CURL or web browser to send the GET /{db}/_session/{sessionid} to the SGW. Maybe you may need to use admin port.

Please let me know the result.

**Comment by HanzhiDou** [comment] 2016-08-31 04:02
@pasin 

I tried on CBL 1.2.1 and CBL 1.3, sessionIds are same and valid:

There are two different sessions for two different databases simultaneously.

Using admin port:

```
$ http localhost:4985/db1/_session/0e90daa311cc7134ce6ead2cf096c13b1dbe41f0
HTTP/1.1 200 OK
Content-Length: 111
Content-Type: application/json
Date: Wed, 31 Aug 2016 03:50:46 GMT
Server: Couchbase Sync Gateway/1.1.1

{
    "authentication_handlers": [
        "default",
        "cookie"
    ],
    "ok": true,
    "userCtx": {
        "channels": {
            "!": 1,
            "u5": 19552
        },
        "name": "5"
    }
}

$ http localhost:4985/db2/_session/7f1ba6fe0065f08bdc5c84fe8d1f1c6b7f600c0f
HTTP/1.1 200 OK
Content-Length: 109
Content-Type: application/json
Date: Wed, 31 Aug 2016 03:49:33 GMT
Server: Couchbase Sync Gateway/1.1.1

{
    "authentication_handlers": [
        "default",
        "cookie"
    ],
    "ok": true,
    "userCtx": {
        "channels": {
            "!": 1,
            "u5": 319
        },
        "name": "5"
    }
}

```

From Client:
```
$ http <proxyIP>/sg/db1/ 'Cookie:SyncGatewaySession=0e90daa311cc7134ce6ead2cf096c13b1dbe41f0'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 183
Content-Type: application/json
Date: Wed, 31 Aug 2016 03:30:52 GMT
Set-Cookie: SERVERID=a9e9752fc4b93d06f52a2859176afbff|1472614252|1472614252;Path=/

{
    "committed_update_seq": 658630,
    "compact_running": false,
    "db_name": "db1",
    "disk_format_version": 0,
    "instance_start_time": 1467615247523062,
    "purge_seq": 0,
    "update_seq": 658630
}


$ http <proxyIP>/sg/db2/ 'Cookie:SyncGatewaySession=7f1ba6fe0065f08bdc5c84fe8d1f1c6b7f600c0f'
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 187
Content-Type: application/json
Date: Wed, 31 Aug 2016 03:36:14 GMT
Set-Cookie: SERVERID=993d42e940874d3660a63df9a870fe28|1472614574|1472614574;Path=/

{
    "committed_update_seq": 3226,
    "compact_running": false,
    "db_name": "db2",
    "disk_format_version": 0,
    "instance_start_time": 1468948688585848,
    "purge_seq": 0,
    "update_seq": 3226
}
```

There are also exceptions using CBL1.2.1, however the sync can succeed.

Exceptions on CBL1.2.1:

```
W/ChangeTracker: ChangeTracker{http://120.55.150.112/sg/cugefit_workout_summary_db, OneShot, @66dcba3}: Exception in change tracker
                                                                          org.apache.http.MalformedChunkCodingException: Chunked stream ended unexpectedly
                                                                              at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:227)
                                                                              at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:188)
                                                                              at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:160)
                                                                              at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
                                                                              at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
                                                                              at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2777)
                                                                              at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2772)
                                                                              at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:652)
                                                                              at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:443)
                                                                              at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:473)
                                                                              at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:330)
                                                                              at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
                                                                              at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
                                                                              at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
                                                                              at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:368)
                                                                              at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:231)
                                                                              at java.lang.Thread.run(Thread.java:833)

```

Errors on CBL 1.3


```
W/ChangeTracker: ChangeTracker{http://120.55.150.112/sg/cugefit_workout_summary_db, OneShot, @b25118a}: Change tracker got error 401
W/Sync: Change tracker stopped during continuous replication

```

**Comment by pasin** [comment] 2016-08-31 04:29
I have never tried to use 2 sessions of the same user to sync to the same remote db on the Sync Gateway. But in theory, I think it should work. @adamcfraser do you see any issues with this or is there anything that should be aware of regarding session management on SGW side.

**Comment by pasin** [comment] 2016-08-31 04:45
@HanzhiDou I don't know for sure if this issue is the same as https://github.com/couchbase/couchbase-lite-android/issues/817 or not, but it could be. 

We are closing down 1.3.1 release that contains several hot fix the issue 817 above and a few other fixes related POST _replicate. Do you mind to test the app with 1.3.1 ([download link](http://latestbuilds.hq.couchbase.com/couchbase-lite-phonegap/release/1.3.1/1.3.1-10/Couchbase-Lite-PhoneGap-Plugin_1.3.1-10.zip))? It might also a good idea to test with SGW 1.3 as well.

**Comment by HanzhiDou** [comment] 2016-08-31 04:48
@pasin  two sessions for two different remote dbs, not one same remote db.

I will try 1.3.1 and also SGW 1.3, perhaps not very soon due to too many things to do recently.

**Comment by pasin** [comment] 2016-08-31 04:53
> @pasin two sessions for two different remote dbs, not one same remote db.
Oh, I see. I understand it wrong.

> I will try 1.3.1 and also SGW 1.3, perhaps not very soon due to too many things to do recently.
No problems. Please let me now. If I come across anything related to the issue, I will update. Thanks.

**Comment by HanzhiDou** [comment] 2016-08-31 07:19
@pasin I used you provided 1.3.1 CBL cordova plugin and got still same Unauthorized error.

I tested more still using CBL 1.3.1 and got new findings.

My deployment infra also has one load balancer, which connects to two nginx proxy server, it proxy to local sync gateway in same server. 

when the sync request  to the sync gateway port 5984 directly, pull and push sync works! and also works using nginx on the same server. 

So the problem is related to the load balancer (one cloud service provided by aliyun), there might be something changed in CBL 1.3 which affects the load balancer behaviour.

**Comment by HanzhiDou** [comment] 2016-08-31 07:25
The load balancer in cloud service provider has very limited configuration and no changes when i upgrade CBL to 1.3.

Though CBL 1.3.1 sync works, there are also exceptions:

```
OneShot, @14e47e2}: Exception in change tracker
                                                                           java.net.SocketTimeoutException: timeout
                                                                               at okio.Okio$3.newTimeoutException(Okio.java:212)
                                                                               at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
                                                                               at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
                                                                               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                               at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                               at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
                                                                               at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
                                                                               at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
                                                                               at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
                                                                               at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
                                                                               at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
                                                                               at okhttp3.RealCall.getResponse(RealCall.java:244)
                                                                               at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                                                                               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                               at okhttp3.RealCall.execute(RealCall.java:57)
                                                                               at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:332)
                                                                               at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:246)
                                                                               at java.lang.Thread.run(Thread.java:833)
                                                                            Caused by: java.net.SocketTimeoutException
                                                                               at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                               at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                               at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                               at okio.Okio$2.read(Okio.java:140)
                                                                               at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
                                                                               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) 
                                                                               at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) 
                                                                               at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) 
                                                                               at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184) 
                                                                               at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125) 
                                                                               at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775) 
                                                                               at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86) 
                                                                               at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760) 
                                                                               at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613) 
                                                                               at okhttp3.RealCall.getResponse(RealCall.java:244) 
                                                                               at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201) 
                                                                               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163) 
                                                                               at okhttp3.RealCall.execute(RealCall.java:57) 
                                                                               at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:332) 
                                                                               at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:246) 
                                                                               at java.lang.Thread.run(Thread.java:833) 
```

another error  (CBL 1.3.1):

```
 W/database: SQLiteConnectionPool: The connection pool for database '/data/user/0/com.cugesoft.fitnessmobile/files/workout_db.cblite2/db.sqlite3' has been unable to grant a connection to thread 5190 (CBLReplicationExecutor-http://<ip>:4984/cugefit_workout_db-push-6323a) with flags 0x2 for 167.755 seconds.
      Connections: 0 active, 1 idle, 2 available.

```

**Comment by HanzhiDou** [comment] 2016-08-31 07:35
BTW, if I use the load balancer to check session validation, like http <load_balancer_ip>/sg/db1/ 'Cookie:SyncGatewaySession=<sessionId>',  the response is correct.

**Comment by hideki** [comment] 2016-09-14 00:53
ToDo:
- Test CBL Android 1.3.1 against SG 1.1.x without authentication
-  Test CBL Android 1.3.1 against SG 1.1.x with authentication (Cookie)

**Comment by hideki** [comment] 2016-09-14 00:59
Hi @HanzhiDou,
Can you capture data between CBL Android and Proxy, and also between Proxy and Sync Gateway? And can you capture Sync Gateway Log?

**Comment by hideki** [comment] 2016-10-19 22:22
Hi @HanzhiDou,
Do you have any updates for this ticket?

**Comment by HanzhiDou** [comment] 2016-10-20 05:37
@hideki sorry, I don't have time to dig this deep more, I removed the load balancer, it works so far.

**Comment by hideki** [comment] 2016-10-20 05:47
@HanzhiDou Thank you for your update. I will close this ticket. If you face this issue again, please reopen the ticket. Thanks!

**Closed by hideki** 2016-10-20 05:47 UTC
Labels: needsmoreinfo, reproduce/investigate, review

**Comment by NitzDKoder** [comment] 2017-09-15 17:53
@hideki we randomly see java.net.SocketTimeoutException connect timeout in cbl 1.4.0.
Will setting write timeout to 30 secs to 10secs will slove? Any other reasons?
Pls confirm

**Comment by hideki** [comment] 2017-09-15 18:32
Hi @NitzDKoder,
If timeout is set to 30 sec, it takes 30 sec to identify some of the network problems. It causes other problems. Best timeout value could be different for every environment and/or application. Currently, I don't have the plan to change the default timeout value. However, you could experiment with different timeout value with your environment.

**Comment by NitzDKoder** [comment] 2017-09-16 00:07
@hideki its got and change tracker is retrying..as you said its network dependent will equirement with higher value..say 15 secs etc..


Other problems you mean retry will be late? Or any other?

**Comment by hideki** [comment] 2017-09-16 01:30
@NitzDKoder ,
The biggest problem I have observed with higher timeout value is taking a time to identify network connection failure. In case network failure occurs between the server and the client, the client might not be able to detect the problem immediately. It might need to wait till SocketTimeoutException is thrown.
