### ISSUE TITLE
Cordova - After putting Android app in background mode for a few hours, CB lite is unresponsive

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#1296] opened 2016-06-27 16:20 UTC
Issue was originally reported at forums.couchbase.com
https://forums.couchbase.com/t/cordova-after-putting-android-app-in-background-mode-for-a-few-hours-cb-lite-is-unresponsive/8833

```
Hey everyone,

As stated in the subject line, my Cordova app running on Android is experiencing issues with connecting to CB lite after the app has been put in background mode for a number of hours. This is happening to all of my Android users and me.

When I look at the network log of the traffic of the app after resumption, all CB lite calls are pending.

I need urgent help on this as it's killing user adoption on Android. I'm not experiencing this issue on IOS.

Is there a inactivity timeout setting I can adjust?
```

**Comment by atgillette** [comment] 2016-06-30 23:30
@hideki,

Would you mind giving me an ETA for this?

**Comment by hideki** [comment] 2016-06-30 23:41
Hi @atgillette,

Honestly speak, this issue is important for us. But we have many critical issues now. So this ticket is still in the queue. If this is critical for you, please escalate from your couchbase contact person?

Thank you.

**Comment by atgillette** [comment] 2016-06-30 23:55
Thanks @hideki for getting back to me.  I'll reach out to my contact.

**Comment by atgillette** [comment] 2016-07-01 21:09
@hideki,

Fujio thinks that this issue will be assigned to 1.3.  Can you confirm with me?

**Comment by hideki** [comment] 2016-07-01 22:12
Hi @atgillette,
Currently I am not sure how difficult to fix this issue. During next week or at least before 1.3 release, I will take a look. Then we can decide. Listener (web server) issue is sometimes challenging to fix it.

**Comment by atgillette** [comment] 2016-07-01 22:19
@hideki,

Thanks for letting me know.  This is absolutely critical to the release of my app.

**Comment by atgillette** [comment] 2016-07-29 04:07
Hi @hideki,

What happened to this ticket?  I thought it was in ready state.

**Comment by hideki** [comment] 2016-07-29 19:49
Sorry, I could not solve this issue yet.

**Comment by atgillette** [comment] 2016-07-30 05:41
I understand @hideki.

**Comment by atgillette** [comment] 2016-08-05 14:18
@hideki,

Is there anyway you can get this issue fixed in a 1.3 patch release?

**Comment by pasin** [comment] 2016-08-10 00:06
So far I couldn't get reproduce the issue with todolite-phonegap. I'm using Nexus 5x with Android 6.0.1. 

What I did:
1. Put the app into the background
2. Make the phone into the lock-screen mode
3. Wait for 30+ mins and then check if I can still use the app (e.g. create a new task list).

@atgillette Can you review the step that I list above? and Can you provide some info about Android OS / device?

**Comment by atgillette** [comment] 2016-08-10 14:56
Hi @pasin,

I'm able to reproduce the issue on the Todo app.  Here are the steps I used to reproduce the issue:

1.  start Todo app - Phonegap version
2. Create a couple of lists and add some tasks
3. Put app in background mode overnight
4. Return to app.  Lists no longer appear

I'm not able to give you a specific duration for how long the app needs to be in background mode.  Sometimes 30 minutes is sufficient.  But sometimes it takes longer.  It's best to leave it in background mode for about an hour.

As for Android OS / device/CBL:
- 6.0.1
- Nexus 5 
- 1.2.1

**Comment by pasin** [comment] 2016-08-10 15:43
OK, I will try to reproduce it again today.

**Comment by pasin** [comment] 2016-08-10 15:44
Anyway v1.3.0 is already out. You could try with 1.3.0 as well.

**Comment by pasin** [comment] 2016-08-10 19:26
I think I was able to reproduce the same behavior with todo-lite phonegap after leaving it in the background for about an hour. After bringing the app to the foreground, I can still see the list but I couldn't create a new list. I could debug it and I could see that the request to create a new list was submitted but was timeout.

I captured the thread dump and posted below. From the thread dump, there are 6 connections (from the conn pool) waiting to read the result. I don't know the max # of connections can be created, but I guessed it reached the maximum. I suspected that those 6 connections are longpoll changes feed request. It's not clear at that point what makes them pending like.

Thread dump:
```
Full thread dump

"Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@8c5af37@5173" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(0)-PooledThread: Acme.Serve.Serve$ServeConnection@8c5af37@5173
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:61)
	  - locked <0x1466> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:151)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1445> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@5bba40e@5174" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(1)-PooledThread: Acme.Serve.Serve$ServeConnection@5bba40e@5174
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:61)
	  - locked <0x146d> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:151)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1447> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool(2)-PooledThread: Acme.Serve.Serve$ServeConnection@b5ecc3c@5225" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(2)-PooledThread: Acme.Serve.Serve$ServeConnection@b5ecc3c@5225
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:61)
	  - locked <0x146e> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:151)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x146f> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool(3)-PooledThread: Acme.Serve.Serve$ServeConnection@6a7028@5226" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(3)-PooledThread: Acme.Serve.Serve$ServeConnection@6a7028@5226
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:61)
	  - locked <0x1470> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:151)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1471> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@c0a66d4@5227" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(4)-PooledThread: Acme.Serve.Serve$ServeConnection@c0a66d4@5227
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:61)
	  - locked <0x1472> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:151)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1473> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"Acme.Utils.ThreadPool(5)-PooledThread: Acme.Serve.Serve$ServeConnection@d111c40@5228" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks Acme.Utils.ThreadPool(5)-PooledThread: Acme.Serve.Serve$ServeConnection@d111c40@5228
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at com.couchbase.lite.router.BufferInputStream.read(BufferInputStream.java:61)
	  - locked <0x1474> (a com.couchbase.lite.router.ByteBuffer)
	  at java.io.InputStream.read(InputStream.java:162)
	  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:151)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
	  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
	  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
	  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
	  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
	  - locked <0x1475> (a Acme.Utils$ThreadPool$PooledThread)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #1@5145" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #1@5145
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1439> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"pool-2-thread-1@5146" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks pool-2-thread-1@5146
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x143a> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #2@5154" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #2@5154
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x143b> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #3@5155" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #3@5155
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x143c> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1038)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"Thread-739@5159" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.accept(Posix.java:-1)
	  at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	  at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:89)
	  at java.net.ServerSocket.implAccept(ServerSocket.java:217)
	  - locked <0x143e> (a java.net.ServerSocket)
	  at java.net.ServerSocket.accept(ServerSocket.java:141)
	  at Acme.Serve.SimpleAcceptor.accept(SimpleAcceptor.java:40)
	  at Acme.Serve.Serve.serve(Serve.java:809)
	  at com.couchbase.lite.listener.LiteServer.serve(LiteServer.java:63)
	  at com.couchbase.lite.listener.LiteListener.run(LiteListener.java:90)
	  at java.lang.Thread.run(Thread.java:818)

"FinalizerDaemon@5140" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerDaemon@5140
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x1437> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
	  at java.lang.Thread.run(Thread.java:818)

"main@5137" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.app.ActivityThread.main(ActivityThread.java:5417)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

"cr.CleanupReference@5157" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks cr.CleanupReference@5157
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x143d> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at org.chromium.content.common.CleanupReference$1.run(CleanupReference.java:51)

"FinalizerWatchdogDaemon@5141" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerWatchdogDaemon@5141
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:255)
	  - locked <0x1438> (a java.lang.Daemons$FinalizerWatchdogDaemon)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:227)
	  at java.lang.Thread.run(Thread.java:818)

"ReferenceQueueDaemon@5139" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks ReferenceQueueDaemon@5139
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:147)
	  - locked <0x1061> (a java.lang.Class)
	  at java.lang.Thread.run(Thread.java:818)

"ConnectivityManager@5156" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"JavaBridge@5170" prio=7 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"HeapTaskDaemon@5142" daemon prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	  at dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java:-1)
	  at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:355)
	  at java.lang.Thread.run(Thread.java:818)

"Session cleaner@5160" prio=1 sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks Session cleaner@5160
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at java.lang.Thread.sleep(Thread.java:1031)
	  - locked <0x143f> (a java.lang.Object)
	  at java.lang.Thread.sleep(Thread.java:985)
	  at Acme.Serve.Serve$2.run(Serve.java:753)
	  at java.lang.Thread.run(Thread.java:818)

"KeepAlive cleaner@5161" daemon prio=5 sleeping
  java.lang.Thread.State: TIMED_WAITING
	 blocks KeepAlive cleaner@5161
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at java.lang.Thread.sleep(Thread.java:1031)
	  - locked <0x1440> (a java.lang.Object)
	  at java.lang.Thread.sleep(Thread.java:985)
	  at Acme.Serve.Serve$KeepAliveCleaner.run(Serve.java:1610)

"Signal Catcher@5138" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"Binder_1@5143" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_2@5144" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_DBThread@5147" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_FileUserBlockingThread@5148" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_ProcessLauncherThread@5149" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_CacheThread@5150" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_IOThread@5151" prio=7 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_FileThread@5152" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-733@5153" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-738@5158" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_InProcRendererThread@5163" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"RenderThread@5164" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-745@5165" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_InProcGpuThread@5166" prio=7 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_3@5167" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-748@5168" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-749@5169" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-753@5172" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-760@5241" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-764@5245" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-765@5246" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-767@5261" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-768@5262" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended
```

**Comment by pasin** [comment] 2016-08-10 19:32
@atgillette would it be possible to provide the thread dump?

**Comment by atgillette** [comment] 2016-08-10 22:11
@pasin,

I'll try tonight.  I'm not how to do it for a cordova app.

**Comment by atgillette** [comment] 2016-08-10 22:12
@pasin,

Did you encounter the issue on both 1.2.1 and 1.3.0?

**Comment by pasin** [comment] 2016-08-10 22:34
I'm testing on 1.3.0.  I got the thread dump by importing the project to the Android Studio and run the project. After running the project on the device, from the menu, I selected `Run > Attach Debugger to Android process`. After that I selected `Run > Get Thread Dump`.

I knew that there is a way to get the thread dump by using `adb` command as well but I have never tried that.

**Comment by pasin** [comment] 2016-08-10 23:40
The ToDoLite Phonegap issue happens when the longpoll GET /_changes request is timeout. When the request is timeout and probably aborted by the JS HTTP Client used by the app, CouchbaseLite Listener cannot detect the abortion and keeps holding the connection thread and waiting for the changes. The problem was that after the timeout, a new GET /_changes request will be sent. Therefore up to one point, the connections in the pool will be all used and are in the waiting state - no more new requests can be processed. This behavior is very similar to the half-close connection that the other side doesn't get informed about the close (I don't know both the JS HTTP Client and TJWJ well enough to confirm this).

A simple way to solve this is to set `heartbeat` to the GET /_changes request so that the half-close connection can be detected from the lite side. However, I did try this but it doesn't solve the issue. It turns out there is also another issue. The [request](https://github.com/request/request) HTTP client library that [coax](https://github.com/jchris/coax) is using doesn't seem to abort the requests properly when the library detects the timeout. Note that the request library referenced by coax is quite old.

I did an experiment by changing from coax to XMLHttpRequest only for longpoll GET /_changes requests, and the XMLHttpRequest seems to close the request properly after the timeout. Along with the `heartbeat` settings, there is no connection thread leak anymore.

**Comment by pasin** [comment] 2016-08-10 23:48
@atgillette Thread dump can help confirm that the issue that you are having is same issues as todolite-phonegap.

Also are you sending longpoll /GET _changes requests in your app? What HTTP Client library are you using?

**Comment by atgillette** [comment] 2016-08-14 16:00
Hi @pasin,

Apologies for getting back to you so late.  Yes, I'm using the coax library in my project with the default setting, which I believe is longpolling.  I'll look into switching it out for XMLHttpRequest.  

Are there any plans replace or update the coax library?

**Comment by pasin** [comment] 2016-08-14 19:37
@atgillette I would suggest to try to apply the heartbeat only solution. If you set the heartbeat to the value lower than the request timeout (e.g. 20 seconds), the request shouldn't be timeout. If you still encounter the issue after that, you could try to replace coax with XMLHttpRequest for longpoll _changes feed request.

I have just implemented the default timeout to the GET _changes for 1.3.1 which should prevent the dead connection issues regardless. I don't know the release date for 1.3.1 yet but it shouldn't be very long.

**Comment by atgillette** [comment] 2016-08-15 04:22
@pasin, is that a configuration setting in coax?  If so, how do I set that?

**Comment by pasin** [comment] 2016-08-15 17:54
@atgillette I believe coax's changes() function accepts a custom parameter. You can try something like this to set the heartbeat:

```
config.db.changes({since : last_seq, heartbeat: 20000}, function(err, change){
...  
})
```

**Comment by atgillette** [comment] 2016-08-17 04:56
@pasin,
After using the heartbeat setting, my app on iOS stopped getting updates.  So I removed it.

**Closed** 2016-08-18 22:10 UTC
Labels: bug, P1: high, review

**Comment by geraldapeoples** [comment] 2018-05-08 08:36
I am having a similar issue with 1.4.1 phonegap plugin ... when I put the app into background and come back to it next day, sync is not working at all. I need to close the app completely and restart it for sync to work.
