### ISSUE TITLE
View update skips winning revisions

### ISSUE THREAD

**Issue by saubaer** [couchbase/couchbase-lite-java-core#709] opened 2015-08-20 11:43 UTC
Sadly it's hard to reproduce in an isolated environment.
If there are two conflicting revisions, and one of those is deleted, the view update skips the new winnig revision so the document isn't indexed.

For example:
``` 
seq  | doc_id | revid | parent | current | deleted
-----+--------+-------+--------+---------+--------
2750 | 172    | 1-77  | NULL   | 0       | 0
2751 | 172    | 2-1a  | 2750   | 0       | 0
2752 | 172    | 3-0c  | 2751   | 1       | 1
2753 | 172    | 1-6b  | NULL   | 0       | 0
2754 | 172    | 2-1a  | 2753   | 0       | 0
2761 | 172    | 3-d7  | 2754   | 0       | 0
2763 | 172    | 3-06  | 2754   | 1       | 0
2764 | 172    | 4-80  | 2761   | 1       | 1


``` 
(I cut the revid)

"3-d7" and "3-06" are conflicting, "4-80" deletes the branch "3-d7" is in, so i expect "3-06" being the winning revision and thus passed to the view function.
Since all rows of the same doc_id are skipped at:
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteViewStore.java#L351
"3-06" is also skipped, so the document 172 isn't indexed at all.

For me this is fixed by not skipping the rows if the current revision is deleted.
```
while ((keepGoing = cursor.moveToNext()) && !deleted &&
                        (cursor.isNull(0) || cursor.getLong(0) == docID)) {
``` 
I do not understand why the following block (#L358-L391) doesn't find "3-06" as winning revision.

Since it's only 10ish chars, i hope it's ok to not send a PR. :)

**Comment by hideki** [comment] 2015-08-20 17:01
Hi @saubaer, Thank you very much for your issue report.

**Comment by hideki** [comment] 2015-08-20 17:08
Hi @snej,
Can you help me to understand correct behavior? Is current behavior correct, or as user suggested, should other branch's leaf revision be indexed?
Thanks!
Hideki

**Comment by snej** [comment] 2015-08-20 17:29
There's some tricky logic in the index updater for handling a revision that updates a conflict. In a case like the one shown above, the new revision doesn't get indexed (it's a deletion) but it has the side effect of causing a different revision to become the winning one. In the Objective-C code this is handled in CBL_SQLiteViewStorage.m:445-453.

I did a git blame to find out where this code comes from — it was a fix for https://github.com/couchbase/couchbase-lite-ios/issues/578, which you filed as a copy of https://github.com/couchbase/couchbase-lite-android/issues/494. So now I'm confused!

**Comment by saubaer** [comment] 2015-08-20 18:00
Maybe I can add to the confusion:
The case _should_ be handled by the block:
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteViewStore.java#L358-L391

But that only checks for sequences lower than "minLastSequence" so for sequences or revisions not part of the first query ("cursor").
So if the view update would have been triggered for seq. >= 2764 that later block would pick up the seq. 2763 as winner.

In my case, the view update is triggered with a "minLastSequence" of  <= 2763, so the new winning revision "3-06" is in the result list of the first query ("cursor") and is not seen by the 2nd query ("cursor2").

Hope this makes sense.

**Comment by hideki** [comment] 2015-11-25 00:55
Hi @saubaer,

I wrote Unit Test to reproduce the problem. https://github.com/couchbase/couchbase-lite-android/pull/706 . However I could not reproduce it. I believe the fix for [the ticket](https://github.com/couchbase/couchbase-lite-android/issues/494) covers this scenario. If you have time, could you please review my test case?

Thanks!

**Comment by hideki** [comment] 2015-11-25 00:59
Issue is not reproducible with [unit test](https://github.com/couchbase/couchbase-lite-android/pull/706/files) that tries to reproduce this. I believe this scenario is covered by fix of  [the ticket](https://github.com/couchbase/couchbase-lite-android/issues/494). I will close this ticket.

**Closed by hideki** 2015-11-25 00:59 UTC
Labels: bug, in progress, P2: medium, S2: critical, size-medium
