### ISSUE TITLE
Pull replication failed for large pull

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#934] opened 2016-01-21 19:55 UTC
Using CBL Android 1.2.0-sqlite

I was using https://github.com/couchbaselabs/GrocerySync-Android targeting a demo server http://demo-mobile.couchbase.com/grocery-sync/ with 121436 updates. The pull replication failed after a few minutes with the following stack trace. 

```
01-21 11:40:33.321 19166-19179/? V/View: Re-indexing view: grocery-local/byDate
01-21 11:40:33.321 19166-19179/? V/Database: CBLManagerWorkExecutor Begin transaction (level 0)
01-21 11:40:33.321 19166-19179/? E/View: Cannot index view grocery-local/byDate: no map block registered
01-21 11:40:33.321 19166-19179/? V/Database: CBLManagerWorkExecutor CANCEL transaction (level 0)
01-21 11:40:33.331 19166-19179/? E/Query: Exception caught in runAsyncInternal
                                          com.couchbase.lite.CouchbaseLiteException: Cannot index view grocery-local/byDate: no map block registered, Status: 400 (HTTP 400 bad_request)
                                              at com.couchbase.lite.store.SQLiteViewStore.updateIndexes(SQLiteViewStore.java:290)
                                              at com.couchbase.lite.View.updateIndexes(View.java:321)
                                              at com.couchbase.lite.View.updateIndex(View.java:294)
                                              at com.couchbase.lite.Database.queryViewNamed(Database.java:2114)
                                              at com.couchbase.lite.Query$2.run(Query.java:483)
                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:841)
01-21 11:40:33.331 19166-19179/? D/Sync: firing trigger: WAITING_FOR_CHANGES
01-21 11:40:35.521 19166-19179/? D/Sync: com.couchbase.lite.replicator.PullerInternal@42ba0308: saveLastSequence() called. lastSequence: 17429 remoteCheckpoint: {_rev=0-28, lastSequence=17040}
```

**Comment by hideki** [comment] 2016-01-26 22:37
@sethrosetter , 
Can you provide device information you used?

**Comment by sethrosetter** [comment] 2016-01-26 22:39
Nexus 5 running Kit Kat - Android 4.4.4

**Comment by hideki** [comment] 2016-01-27 00:24
2016/01/26

- Nexus 6  (Android 6.0.1) Successfully pulled all revisions twice without this error
- Nexus 9 (Android 6.0.1) Successfully pulled all revisions without this error
- Samsung S3 (Android ) - testing

**Comment by sethrosetter** [comment] 2016-01-27 00:25
Using b733898d1f9441b682e605ab478fb207820befe3 and Nexus 5 - Android 4.4.4,
Successfully pulled all revisions twice.

**Comment by zgramana** [comment] 2016-01-27 01:54
##### Misc notes:

Smells like a race condition, so I started back-tracking from [the location of the exception](https://github.com/couchbase/couchbase-lite-java-core/blob/4586f6a8f8b3ea8cbdb1362196eb5cb00d9b2969/src/main/java/com/couchbase/lite/store/SQLiteViewStore.java#L290). I noticed that the call to [setVersion](https://github.com/couchbase/couchbase-lite-java-core/blob/4586f6a8f8b3ea8cbdb1362196eb5cb00d9b2969/src/main/java/com/couchbase/lite/View.java#L157) isn't wrapped in a `RunInTransaction` block. Any chance there's a race condition here, e.g. multiple HTTP responses interleaving? If so, [this block](https://github.com/couchbase/couchbase-lite-java-core/blob/4586f6a8f8b3ea8cbdb1362196eb5cb00d9b2969/src/main/java/com/couchbase/lite/store/SQLiteViewStore.java#L150-L175) could result in two threads trying to create the view at the same time.

There are some scenarios in Activity-based Android apps where the `onCreate` will fire twice, such as screen rotation and low-memory. We could be leaking by [holding the activity](https://github.com/couchbaselabs/GrocerySync-Android/blob/8c122f9e036cd5f2ca0ab11fc4005fcd57d0f4b8/GrocerySync-Android/src/main/java/com/couchbase/grocerysync/MainActivity.java#L118) context [instead of the application context](http://android-developers.blogspot.com/2009/01/avoiding-memory-leaks.html) in Grocery Sync.

**Comment by sethrosetter** [comment] 2016-01-27 02:39
@zgramana you are correct. I was able to replicate this issue by rotating during a long pull - https://github.com/couchbaselabs/GrocerySync-Android/issues/41

**Comment by hideki** [comment] 2016-01-27 18:07
this is caused by GrocerySync Activity handling.  So I will close this.

**Closed** 2016-01-27 18:07 UTC
Labels: bug, release-prep, reproduce/investigate
