### ISSUE TITLE
Verify if parent rev id is included in revision hash

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-java-core#525] opened 2015-03-26 19:03 UTC
See https://forums.couchbase.com/t/conflict-that-refuses-to-resolve/3326/9?u=traun

**Comment by deanelhard** [comment] 2015-03-26 19:35
It does not include the rev id.  Here is the relevant code from Database.generateIDForRevision:

        // Generate a digest for this revision based on the previous revision ID, document JSON,                                                    
        // and attachment digests. This doesn't need to be secure; we just need to ensure that this                                                 
        // code consistently generates the same ID given equivalent revisions.                                                                      

       try {
            md5Digest = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }

        int length = 0;
        if (previousRevisionId != null) {
            byte[] prevIDUTF8 = previousRevisionId.getBytes(Charset.forName("UTF-8"));
            length = prevIDUTF8.length;
        }
        if (length > 0xFF) {
            return null;
        }
        byte lengthByte = (byte) (length & 0xFF);
        byte[] lengthBytes = new byte[] { lengthByte };

        md5Digest.update(lengthBytes);

        int isDeleted = ((rev.isDeleted() != false) ? 1 : 0);
        byte[] deletedByte = new byte[] { (byte) isDeleted };
        md5Digest.update(deletedByte);

        List<String> attachmentKeys = new ArrayList<String>(attachments.keySet());
        Collections.sort(attachmentKeys);
        for (String key : attachmentKeys) {
            AttachmentInternal attachment = attachments.get(key);
            md5Digest.update(attachment.getBlobKey().getBytes());
        }

        if (json != null) {
            md5Digest.update(json);
        }
        byte[] md5DigestResult = md5Digest.digest();


Note that prevIDUTF8 is generated inside the if block and never used other than to take its length before going out of scope...

the comment says it is part of the algorithm but it is not.

**Comment by hideki** [comment] 2015-03-26 20:55
@deanelhard Thank you very much for all your help!!

**Comment by deanelhard** [comment] 2015-03-30 19:22
I am looking at the modified code, and it is actually still broken...

It seemed to fix the problem because it resulted in a different hash than the one previously created, but it would have the same issue if a 3-way conflict occurred again.

The problem is here:

        byte lengthByte = (byte) (length & 0xFF);
        byte[] lengthBytes = new byte[] { lengthByte };
        md5Digest.update(lengthBytes); // prefix with length byte
        if (length > 0 && prevIDUTF8 != null) {
            md5Digest.update(lengthBytes);
        }

Note that the second digest call digests the length of the parent ID for a second time rather than hashing the value of the parent ID (prevIDUTF8)

**Closed** 2015-03-30 22:01 UTC
Labels: review
