### ISSUE TITLE
Attachment Push failed."java.io.IOException: Unable to load the blob stream for blobKey"

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1675] opened 2017-11-02 12:15 UTC
Hi Folks,
1)CBL 1.4.0 used.

2)[08/22 09:01:38.993] [30393] CBLite: ---> Added: 
```
{s919888880010_ptx1503414316983_a1503414316988_attachment.doc #2-d3a4ef4bd3626eadb271b0e0438076cc @135203} as seq 135203
```
Document with attachment added.

3)@executerequest() 
```
Exception: java.io.IOException: Unable to load the blob stream for blobKey: 87D8CBFF1BCE9EDDC45668905B7D1085D35FE6D9. url: https://919888880010:340668f75a4b6c18875979ca76168244@syncqc3.company.com/ptxdata/s919888880010_ptx1503414316983_a1503414316988_attachment.doc?new_edits=false
java.io.IOException: Unable to load the blob stream for blobKey: 87D8CBFF1BCE9EDDC45668905B7D1085D35FE6D9
at com.couchbase.lite.replicator.BlobRequestBody$1.writeTo(SourceFile:81)
at okhttp3.MultipartBody.writeOrCountBytes(SourceFile:171)
at okhttp3.MultipartBody.writeTo(SourceFile:113)
at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(SourceFile:704)
at okhttp3.internal.http.HttpEngine.readResponse(SourceFile:563)
at okhttp3.RealCall.getResponse(SourceFile:241)
at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
at okhttp3.RealCall.execute(SourceFile:57)
at com.couchbase.lite.replicator.RemoteRequest.executeRequest(SourceFile:261)
at com.couchbase.lite.replicator.RemoteRequest.execute(SourceFile:165)
at com.couchbase.lite.replicator.RemoteRequest.run(SourceFile:105)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
```
java.io.IOException: Unable to load the blob stream for blobKey seen.

@hideki pls share your thoughts.. Logs attached.

[cbl_log_0_3.txt](https://github.com/couchbase/couchbase-lite-java-core/files/1437645/cbl_log_0_3.txt)
Thanks
Nithin

**Comment by hideki** [comment] 2017-11-02 18:07
@NitzDKoder,

From the error, the attachment file for `87D8CBFF1BCE9EDDC45668905B7D1085D35FE6D9` does not exist in the attachment folder. Can you check if the file exists?

Can you create reproduce this problem? If yes, can you share how to reproduce this?

**Comment by NitzDKoder** [comment] 2017-11-03 08:21
@hideki this is random issue.. not sure how to reproduce..


**if CBLite: ---> Added:**

 {s919888880010_ptx1503414316983_a1503414316988_attachment.doc #2-d3a4ef4bd3626eadb271b0e0438076cc @135203} as seq 135203


**Then the attachment folder should have it for sure right?**

Thanks
NIthin

**Comment by hideki** [comment] 2017-11-03 17:34
@NitzDKoder,
I assume that the attachment does not exist in the `attachmens` directory.  Can you check?

**Comment by NitzDKoder** [comment] 2017-11-09 15:27
@hideki what could be the reason for attachment not in directory?
Im unable to reproduce this now..

**Comment by hideki** [comment] 2017-11-09 17:29
@NitzDKoder 
* failed to replicate the file from SG.
* failed to write the file to the disk.
* etc

**Comment by hideki** [comment] 2017-11-09 17:31
@NitzDKoder 
As you can not reproduce the problem, I will close this ticket.
If you encounter the issue again, please reopen this with detailed steps to reproduce the issue?
Thanks!

**Closed by hideki** 2017-11-09 17:31 UTC
Labels: icebox, needsmoreinfo

**Comment by NitzDKoder** [comment] 2017-11-10 10:22
@hideki Its not "failed to replicate the file from SG.".we are trying to push..
**failed to write the file to the disk. Do you see this in logs**
Pls confirm.

**Comment by hideki** [comment] 2017-11-10 19:09
From the log file, I can not find any write operation error.

IOException was thrown because `in` is `null`.
```
            @Override
            public void writeTo(BufferedSink sink) throws IOException {
                InputStream in = blobStore.blobStreamForKey(blobKey);
                if (in == null)
                    throw new IOException("Unable to load the blob stream for blobKey: " + blobKey);
                Source source = null;
                try {
                    source = Okio.source(in);
                    sink.writeAll(source);
                } finally {
                    // close InputStream
                    Util.closeQuietly(source);
                }
            }
```

However, from the log file, we could not find any Error log in the file. So it seems `file.canRead()` returns `false`. 
```
    public InputStream blobStreamForKey(BlobKey key) {
        String path = getRawPathForKey(key);
        File file = new File(path);
        if (file.canRead()) {
            try {
                InputStream is = new FileInputStream(file);
                if (encryptionKey != null)
                    return encryptionKey.decryptStream(is);
                else
                    return is;
            } catch (FileNotFoundException e) {
                Log.e(Log.TAG_DATABASE, "BlobStore: Unexpected file not found in blob store", e);
                return null;
            } catch (SymmetricKeyException e) {
                Log.e(Log.TAG_DATABASE, "BlobStore: Attachment stream " + path + " cannot be decoded!", e);
                return null;
            }
        }
        return null;
    }
```


From the javadoc, `canRead()` return false if the file does not exist or not readable. If the file exists, it could be caused by read-permission of the file.

https://docs.oracle.com/javase/7/docs/api/java/io/File.html#canRead()
> public boolean canRead()
> Tests whether the application can read the file denoted by this abstract pathname.
> Returns:
> true if and only if the file specified by this abstract pathname exists and can be read by the application; false otherwise
> Throws:
> SecurityException - If a security manager exists and its  SecurityManager.checkRead(java.lang.String) method denies read access to the file
