### ISSUE TITLE
CBL - 1.2.0 upgrade from 1.1.0 clears device db

### ISSUE THREAD

**Issue by PureRockets** [couchbase/couchbase-lite-java-core#1161] opened 2016-03-25 20:04 UTC
When using Android Studio with default settings, upgrading from 1.1.0 to 1.2.0 deletes the device local db.

Steps to repro:

    Build any CBL solution in Android Studio with 1.1.0, such as the CouchbaseEvents project in the documentation
    Deploy to simulator or actual device from Android Studio, and write a single document. Verify the document exists by retrieving the document.
    Upgrade to 1.2.0 by updating build.gradle. In the dependencies section, modify the single line:

From:
compile 'com.couchbase.lite:couchbase-lite-android:1.1.0'

To:
compile 'com.couchbase.lite:couchbase-lite-android:1.2.0'

    Redeploy the app
    Attempt to retrieve the document. Note that it no longer exists.

ASK: The upgrade should persist the device db between upgrades

**Comment by hideki** [comment] 2016-03-29 20:26
Hi @PureRockets,
We tested this scenario before releasing v1.2.0. 
Do you have any additional information?
Thanks!
Hideki

**Comment by PureRockets** [comment] 2016-05-13 23:20
No additional information, it's easy to reproduce. Steps are provided above.

**Comment by hideki** [comment] 2016-05-13 23:48
I followed the steps that was described in the ticket. But I still could not reproduce the issue. 
Steps I did:
```
1. Create Android app with CBL v1.1.0
2. In the app, store the one document.
3. Confirmed that the document exists with multiple deployments.
4. Rebuild with app with CBL v1.2.0.
5. Verified the document that was created with CBL v1.1.0 still exists.
```
I guess there is missing information to reproduce the problem.
Thanks,

**Comment by hideki** [comment] 2016-05-14 00:07
I tried to reproduce the issue with using Android Studio v1.5 and v2.0. Both versions can not reproduce the issue.

**Comment by hideki** [comment] 2016-05-14 00:08
As this issue is not reproducible here and no additional information, I will close this ticket. If this is still reproducible with latest version of Couchbase Lite, please reopen the ticket.

**Closed** 2016-05-14 00:08 UTC
Labels: bug, customer, reproduce/investigate
