### ISSUE TITLE
Views broken with concurrent update and delete

### ISSUE THREAD

**Issue by ethanfrey** [couchbase/couchbase-lite-java-core#952] opened 2016-01-26 15:02 UTC
Hi guys....

We've spent about a week and a half with a very annoying issue with this library.  We moved our server from CouchDB to Sync Server to resolve it (finding other issues like https://github.com/couchbase/sync_gateway/issues/1505 in the meantime).  And changed out server logic a few times, and watched the change feeds. But the bug still persists and is quite annoying.  Now we have clearly tracked it down to the java couchbase lite library.

This is what we do:

- We have an document shared on multiple devices and our server.  Base revision 1-x.
- We have a view function on the client to show all docs of type X, it displays this document.
- The two devices make changes and sync them concurrently (either very good timing, or taking one device offline, editing, then bringing it back online).
-  We now have a conflict between versions 2-a and 2-b on the server.
- So far the view looks good and shows the same (arbitrary) revision on both clients. (View updated well)
- Now, we run a conflict resolution script that marks 2-a as deleted (3-c) and updates 2-b with the merged data (3-d)
- Both these changes are synced in the same _changes query to the couchbase lite client and processed in one batch
- If rev of 3-d > rev of 3-c, everything works fine and we see the merged object in the view
- If rev of 3-d < rev of 3-c, the object is considered deleted on the client, and disappears from the view
  - THIS is the problem

More details:

- All data looks proper on the server
- Also, if we restart the app, the document is still missing from the view (I guess this is not updated again?)
- The custom view function for the view is never triggered by the last update (for either document rev 3-c or 3-d).  We have some log messages there and nothing happens in this case.
- If we wipe the local DB clean, and resync from the server, the document will appear correctly (I guess we trigger different client logic?)
- If we pull out the sqllite store from the client (even with a broken state) and look at the revision table, we see both rev 3-c and 3-d marked as current, and 3-c as deleted, which is proper
- If we look at the maps_N table for this view, it is empty, the document is not there
- Looking at winningRevIDOfDocNumericID (SQLiteStore.java:1971), the query there will calculate the correct winning revision from the data store.

Currently we trigger this only on the server, but I doubt it would be much different if the conflict resolution occurred on a client.  The main point is that one branch is deleted and the second updated in the same batch. And it leave the client in a broken state.

Given that the main use case for Couchbase is the conflict resolution (offline sync), and I figure we are doing a typical form of conflict resolution (update one branch, delete the other), I am quite surprised that this issue hasn't popped up earlier. And seems quite critical to our use case.

Currently, two developers have spent an entire week on the client and server hunting this issue. And this unreliability is threatening to block the adoption of offline sync by our company, which is annoying, as in theory this software matches our use case perfectly.

Please let me know if you need any more help to reproduce this bug.

**Comment by ethanfrey** [comment] 2016-01-26 15:29
P.S. I tried to find some test code for this case, or a similar case and found basically nothing.  There is no test code in couchbase-lite-java-core, and finally I found it in couchbase-lite-android.  But the store layer, which is the basis of everything, in androidTest/java/com/couchbase/lite/{store,storage} contains all of one file with one test case for the most simple conflict detection of two revisions.

Is there a whole suite of test code somewhere else that I am missing, or is it just luck and patches holding together the storage engine?

**Comment by hideki** [comment] 2016-01-27 01:51
Hi @ethanfrey,

Thank you very much for your issue report.

I wrote the unit test to reproduce the problem. See [PR](https://github.com/couchbase/couchbase-lite-android/pull/763). However I could not reproduce the problem. Fix for https://github.com/couchbase/couchbase-lite-android/issues/494 could also fix the issue you are encountering. 
Note: Newly added test is still under review, so it is not yet merged.

Currently v1.2.0 release candidate build is available on couchbase maven repo. Could you please verify if v1.2.0 fixes the issue you are encountering? http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.2.0-18/

Most of view related tests are in https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ViewsTest.java

Thanks,

**Comment by hideki** [comment] 2016-01-27 01:58
As I can not reproduce the problem with v1.2.0, I will close this ticket. 
If you can still  encounter this issue with v1.2.0, please let us know.
Thanks!

**Comment by ethanfrey** [comment] 2016-01-27 15:21
First, thank you for the quick response and the test case.

We could reproduce the problem by slightly modifying the test case in the pull request.  You just need to run update view after the 2-x objects are saved and before the 3-x objects are saved, which is what happens in normal syncing with the server (first, get the conflict state, update view, then get conflict resolution, update view).

We have an idea for a fix as well.  But that comes later...

Please re-open this issue after reviewing the new test case.

**Comment by ethanfrey** [comment] 2016-01-27 15:41
So, we have a bug that reproduces the issue and a fix that needs to be in another pull request.

However, as I was informed in https://github.com/couchbase/sync_gateway/pull/1512#issuecomment-174598528 we must sign a CLA before our code can be accepted by the couchbase project.  However, all attempts to create an account on http://review.couchbase.org/login/%23%2Fregister%2Fq%2Fstatus%3Aopen lead to failure, as google dropped support for openid april 20th 2015, as noted in https://review.openstack.org/Documentation/config-sso.html#_multiple_identities

Since neither of us have yahoo, aol, wordpress accounts, this makes it near impossible to sign into the garrett code review site to sign the CLA.  Is there any other way to log into the account?

**Comment by zgramana** [comment] 2016-01-27 15:48
I apologize for that. We are working to improve that. In meanwhile, most contributors are creating a new Yahoo account just for this. Will that work for you?

**Closed** 2016-02-08 21:13 UTC
Labels: bug, reproduce/investigate, review
