### ISSUE TITLE
 Could not allocate CursorWindow

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-java-core#440] opened 2015-02-17 04:52 UTC
Replication work in background (Continuous). After 18-30 hour application crash in error:

02-17 09:12:35.981: E/CursorWindow(14399): Could not allocate CursorWindow '/data/data/ru.edgex.quickresto/files/qrbox_db.cblite' of size 2097152 due to error -12.
02-17 09:12:36.001: E/CursorWindow(14399): Could not allocate CursorWindow '/data/data/ru.edgex.quickresto/files/special_db.cblite' of size 2097152 due to error -12.
02-17 09:12:36.001: E/RemoteRequest(14399): RemoteRequestCompletionBlock throw Exception
02-17 09:12:36.001: E/RemoteRequest(14399): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.CursorWindow.<init>(CursorWindow.java:104)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.moveToNext(AndroidSQLiteStorageEngine.java:178)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.Database.changesSince(Database.java:1934)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.replicator.PusherInternal.beginReplicating(PusherInternal.java:261)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.replicator.ReplicationInternal$9.onCompletion(ReplicationInternal.java:787)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:134)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:145)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:305)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:255)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:101)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.lang.Thread.run(Thread.java:841)
02-17 09:12:36.001: E/RemoteRequest(14399): RemoteRequestCompletionBlock throw Exception
02-17 09:12:36.001: E/RemoteRequest(14399): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.CursorWindow.<init>(CursorWindow.java:104)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.moveToNext(AndroidSQLiteStorageEngine.java:178)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.Database.getAttachmentsDictForSequenceWithContent(Database.java:2640)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.Database.extraPropertiesForRevision(Database.java:1298)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.Database.expandStoredJSONIntoRevisionWithAttachments(Database.java:1379)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.Database.changesSince(Database.java:1951)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.replicator.PusherInternal.beginReplicating(PusherInternal.java:261)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.replicator.ReplicationInternal$9.onCompletion(ReplicationInternal.java:787)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequestRetry$1.completed(RemoteRequestRetry.java:134)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequestRetry$1.onCompletion(RemoteRequestRetry.java:145)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequest.respondWithResult(RemoteRequest.java:305)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequest.executeRequest(RemoteRequest.java:255)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at com.couchbase.lite.support.RemoteRequest.run(RemoteRequest.java:101)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-17 09:12:36.001: E/RemoteRequest(14399): 	at java.lang.Thread.run(Thread.java:841)

Any access to the database is:

02-17 09:44:23.941: E/AndroidRuntime(14399): FATAL EXCEPTION: main
02-17 09:44:23.941: E/AndroidRuntime(14399): Process: ru.edgex.quickresto, PID: 14399
02-17 09:44:23.941: E/AndroidRuntime(14399): android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.database.CursorWindow.<init>(CursorWindow.java:104)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.moveToNext(AndroidSQLiteStorageEngine.java:178)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at com.couchbase.lite.Database.getLastSequenceNumber(Database.java:294)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at com.couchbase.lite.Database.getAllDocs(Database.java:2182)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at com.couchbase.lite.Database.queryViewNamed(Database.java:2070)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at com.couchbase.lite.Query.run(Query.java:350)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at ru.edgex.quickresto.managers.AbstractEntityManager.getEntities(AbstractEntityManager.java:95)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at ru.edgex.quickresto.managers.AbstractEntityManager.getEntitiesFromAllDocumentsQuery(AbstractEntityManager.java:84)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at ru.edgex.quickresto.managers.DeviceInfoManager.getDeviceInfo(DeviceInfoManager.java:43)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at ru.edgex.quickresto.fragments.PersonalDevicesFragment.createList(PersonalDevicesFragment.java:132)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at ru.edgex.quickresto.fragments.PersonalDevicesFragment.onCreateView(PersonalDevicesFragment.java:82)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1504)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:482)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.View.measure(View.java:16820)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.View.measure(View.java:16820)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.View.measure(View.java:16820)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.View.measure(View.java:16820)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.View.measure(View.java:16820)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5156)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2295)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.View.measure(View.java:16820)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1962)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1156)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1341)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1043)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
02-17 09:44:23.941: E/AndroidRuntime(14399): 	at android.view.Choreograph

**Comment by hideki** [comment] 2015-02-17 05:17
Hi @QRPro,

Thank you for reporting the issue. To understand the issue better, could you please provide us more information about it. Following is bug report guideline: https://github.com/couchbase/couchbase-lite-java-core/blob/master/CONTRIBUTING.md

Thanks!

**Comment by QRPro** [comment] 2015-02-17 06:17
1) Version couchbase lite 1.0.3.1
2) A simple application starts continious replication. No other action occurs.
3) On the server side, the frequent changes of documents.
4) Communication with the server is not stable. Frequent breaks.

**Comment by hideki** [comment] 2015-02-17 19:24
Hi @QRPro,

There are two possibilities which causes this issue.
- document size is larger than 2MB. see https://github.com/couchbase/couchbase-lite-android/issues/357
- cursor leak: [link to stackoverflow](http://stackoverflow.com/questions/17495713/could-not-allocate-cursorwindow)

In case issue is caused by document size, it is current limitation of CBL Android because CBL Android relies on SQLite.

In case the issue is caused by cursor leak, this is also hard to identify the root cause. All of cursors are opened in try - catch - finally blocks, and all cursors are closed in its finally block. From code review point of view, we can not find potential problem.

We will keep our eye open for this ticket.

**Comment by QRPro** [comment] 2015-02-18 10:45
We do not create large documents, the problem is likely to leak. Let's wait for news.

**Comment by hideki** [comment] 2015-03-14 05:50
Hi @QRPro,
I believe root cause of this issue is Out of Memory which is caused by pull replication with large document and many documents. We fixed the issue #447 recently. I believe root cause is same. Please try CBL Android from master branch? I will close this ticket now. If the issue is still reproducible with master branch, please reopen the ticket.
Thanks!

**Closed by hideki** 2015-03-14 05:50 UTC
Labels: backlog, needsmoreinfo

**Comment by chaozaiai** [comment] 2016-03-29 11:39
1.document size is larger than 2MB. see couchbase/couchbase-lite-android#357
2.cursor leak: link to stackoverflow
To the seond problem , i think we can use cursor careful and remember to close it correctly.
But, to the first problem, how can i  avoid this exception? Or what to do to find the code which lead to  this problem?

**Comment by hideki** [comment] 2016-03-29 15:33
@chaozaiai,

1. Since v1.2.0, CBL Android support document size > 2MB.
2. CBL uses finally block to close cursor. From code review point of view, CBL should not have cursor leak anymore.
