### ISSUE TITLE
ToDoLite App's progress indicator never stops.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#389] opened 2015-01-19 22:36 UTC
ToDoLite app set enable/disable based on replicator's status.
- If REPLICATION_ACTIVE, enable the indicator
- Otherwise, disable the indicator.

It seems CBL java core sends state of RUNNING or IDLE in stead of ACTIVE or IDLE.

**Comment by tleyden** [comment] 2015-01-19 22:53
That's surprising, I just dug into a very similar sounding problem in https://github.com/couchbase/couchbase-lite-java-core/issues/383, and retested on TodoLite.

Can you post exact steps on how to reproduce?

**Comment by hideki** [comment] 2015-01-19 23:02
Condition
- I use ToDoLite from master branch. Not Google Play version.
- Tested on Genymotion emulator with Android SDK 4.4.4 API 19

Step1
1. Type any new task in text field.
2. Take photo for the task
3. Observed new task was synced to other device.
4. Indicator is still spinning.

**Comment by tleyden** [comment] 2015-01-19 23:10
Can you double-check which couchbase-lite-java-core and couchbase-lite-android version is being used?  Are the submodule pointers pointing to the latest (or near latest) commits on the master branch of each repo?

**Comment by hideki** [comment] 2015-01-19 23:16
Android: 37fefc7 (latest)
Java Core: b019243 (my branch from master (near latest))

**Comment by tleyden** [comment] 2015-01-19 23:19
Ok, looks like you have the commit for the #383 fix.  We'll need to dig into the root cause.

**Comment by hideki** [comment] 2015-01-19 23:22
Java core sends state change event to ToDo Lite app. But its state is not expected one for ToDo Lite app.

**Comment by hideki** [comment] 2015-01-19 23:29
Last week @WilliamHoang showed me slow replication of Office Radar app on Android. Actually replication was never finished during we had been observing. I guess this issue would make Office Radar app confused about replication status If office-radar uses similar event-handling logic with ToDoLite app.

**Comment by tleyden** [comment] 2015-01-21 19:21
I'm pretty sure this is the same bug as https://github.com/couchbase/couchbase-lite-java-core/issues/383.  Closing as a duplicate.

**Comment by hideki** [comment] 2015-02-03 01:46
After fixing #383, I still observes this TODO Lite indicator issue. I should investigate deeper.

**Comment by hideki** [comment] 2015-02-05 02:09
Note to self:

Root cause of this issue
- ToDo Lite starts both push and pull replicators.
- Add new task. App store doc (task) into database.
- Push replicator push new doc onto SG. and Done.
- Pull replicator sends check point to SG. and state becomes ACTIVE.
- Problem: After the completion of check point, pull replicator status does not back to IDLE.

Solution:
- call fireTrigger(ReplicationTrigger.WAITING_FOR_CHANGES); after check point line 1569 of ReplicationInternal.java

TODO:
- Write Unit Test case for this.

**Closed** 2015-02-06 02:30 UTC
Labels: review
