### ISSUE TITLE
P2P - SQLiteReadOnlyDatabaseException error

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-java-core#427] opened 2015-02-13 01:16 UTC
Pulling 100 documents from a remote device (with Listener running) OR pushing 100 documents from a client to a remote device causes SQLiteReadOnlyDatabaseException as below:

```
02-12 17:01:12.397    9633-9750/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
02-12 17:01:12.397    9633-9750/couchbase.com.myp2p E/Sync﹕ PullerInternal stopGraceful.run() finished
02-12 17:01:12.412    9633-9757/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
02-12 17:01:12.420    9633-9752/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
02-12 17:01:12.879    9633-9759/couchbase.com.myp2p E/Sync﹕ batcher.waitForPendingFutures()
02-12 17:01:12.888    9633-9760/couchbase.com.myp2p E/Sync﹕ batcher.waitForPendingFutures()
02-12 17:01:12.921    9633-9651/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => RESUME
02-12 17:01:12.925    9633-9759/couchbase.com.myp2p E/Sync﹕ waitForPendingFutures()
02-12 17:01:12.929    9633-9710/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => RESUME
02-12 17:01:12.930    9633-9760/couchbase.com.myp2p E/Sync﹕ waitForPendingFutures()
02-12 17:01:12.934    9633-9694/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => RESUME
02-12 17:01:12.939    9633-9763/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
02-12 17:01:12.941    9633-9766/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
02-12 17:01:13.344    9633-9769/couchbase.com.myp2p W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
02-12 17:01:13.425    9633-9651/couchbase.com.myp2p E/SQLiteLog﹕ (1032) statement aborts at 17: [INSERT INTO docs(docid) VALUES (?)]
02-12 17:01:13.426    9633-9651/couchbase.com.myp2p E/SQLiteDatabase﹕ Error inserting docid=2d4d6d0b-07af-4b08-b93f-8fc818aa7d9c
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:116)
            at com.couchbase.lite.Database.insertDocumentID(Database.java:3299)
            at com.couchbase.lite.Database.getOrInsertDocNumericID(Database.java:3313)
            at com.couchbase.lite.Database.forceInsert(Database.java:3948)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:510)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:96)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:221)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:44)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
02-12 17:01:13.432    9633-9651/couchbase.com.myp2p E/SQLiteLog﹕ (787) abort at 51 in [INSERT INTO revs(doc_id,revid,no_attachments,deleted,current,json) VALUES (?,?,?,?,?,?)]: FOREIGN KEY constraint failed
02-12 17:01:13.433    9633-9651/couchbase.com.myp2p E/SQLiteDatabase﹕ Error inserting doc_id=-1 revid=1-aeeec7aba427f3c2fc2828020739a417 no_attachments=true deleted=false current=true json=[B@11ae6964
    android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:116)
            at com.couchbase.lite.Database.insertRevision(Database.java:3495)
            at com.couchbase.lite.Database.forceInsert(Database.java:4017)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:510)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:96)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:221)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:44)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
02-12 17:01:13.434    9633-9651/couchbase.com.myp2p W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@2f1942af: failed to write {2d4d6d0b-07af-4b08-b93f-8fc818aa7d9c #1-aeeec7aba427f3c2fc2828020739a417}: status=500

```

**Comment by hideki** [comment] 2015-03-11 19:13
Another Exception:
This exception happens at P2P server (listener) side.
```
03-11 15:02:43.520    1545-1711/couchbase.com.myp2p E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@52898ab4: Exception in change tracker
    org.apache.http.conn.ConnectTimeoutException: Connect to /10.17.4.99:10000 timed out
            at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:452)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
            at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:322)
            at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:222)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by hideki** [comment] 2015-03-11 20:05
##### InvocationTargetException and SQLiteReadOnlyDatabaseException

This exception occurs at P2P server side (listener) side

Steps
1. At client side, create 1600 documents by clicking button 16 times 
2. At server side, create 400 documents by clicking button 4 times.


```
03-11 13:00:38.874  25079-25116/couchbase.com.myp2p E/SQLiteLog﹕ (1032) statement aborts at 22: [UPDATE localdocs SET revid=?,json=? WHERE docid=? AND revid=?]
03-11 13:00:38.875  25079-25116/couchbase.com.myp2p E/Router﹕ Router unable to route request to do_PUT_Document
    java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
            at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
            at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
            at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
            at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.update(AndroidSQLiteStorageEngine.java:126)
            at com.couchbase.lite.Database.putLocalRevision(Database.java:4391)
            at com.couchbase.lite.router.Router.update(Router.java:1655)
            at com.couchbase.lite.router.Router.update(Router.java:1693)
            at com.couchbase.lite.router.Router.do_PUT_Document(Router.java:1728)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
03-11 13:00:38.956  25079-25079/couchbase.com.myp2p V/TDCollateJSON﹕ SQLite3 handle is -1613729024
```

**Comment by hideki** [comment] 2015-03-11 21:28
##### android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1)

This exception is thrown at listener side.

Steps to reproduce:
1. Create 100 docs on listener side and 100 docs on client side same time.

```
03-11 14:19:35.825  29324-29717/couchbase.com.myp2p E/Router﹕ Router unable to route request to do_POST_Document_bulk_docs
    java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1)
            at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
            at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
            at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
            at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
            at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
            at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.beginTransaction(AndroidSQLiteStorageEngine.java:78)
            at com.couchbase.lite.Database.beginTransaction(Database.java:1253)
            at com.couchbase.lite.router.Router.do_POST_Document_bulk_docs(Router.java:1080)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
    --------- beginning of crash
03-11 14:19:35.840  29324-29324/couchbase.com.myp2p E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: couchbase.com.myp2p, PID: 29324
    java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
            at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
            at android.database.sqlite.SQLiteSession.setTransactionSuccessful(SQLiteSession.java:371)
            at android.database.sqlite.SQLiteDatabase.setTransactionSuccessful(SQLiteDatabase.java:540)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.setTransactionSuccessful(AndroidSQLiteStorageEngine.java:88)
            at com.couchbase.lite.Database.endTransaction(Database.java:1288)
            at com.couchbase.lite.Database.putRevision(Database.java:3775)
            at com.couchbase.lite.Database.putRevision(Database.java:3548)
            at com.couchbase.lite.Document.putProperties(Document.java:417)
            at com.couchbase.lite.Document.putProperties(Document.java:252)
            at couchbase.com.myp2p.MainActivity$2.onClick(MainActivity.java:101)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by tleyden** [comment] 2015-03-11 21:44
Same error as https://github.com/couchbase/couchbase-lite-java-core/issues/481

**Comment by hideki** [comment] 2015-03-11 22:16
I think I introduced this issue by fixing nested-transaction issue.

**Comment by hideki** [comment] 2015-03-11 23:48
SQLiteReadOnlyDatabaseException issue and Transaction (Cannot start a transaction within a transaction) issue are two different issue.
Transaction issue is tracked by different ticket #484

**Comment by hideki** [comment] 2015-03-12 00:36
Steps to reproduce `SQLiteReadOnlyDatabaseException` issue
1. Install P2P listener app and P2P client app to two different devices.
2. Create 100 documents at P2P client side (not P2P listener side). <- I am not sure if 100 docs are required. It could be reproducible with 1 document.
3. P2P Listener app throws  `SQLiteReadOnlyDatabaseException` exception

Note: 
- Http Listener server runs with different thread (not main thread). Accessing database from non-main thread might causes issue. However this issue is not reproducible (or not easily) if initial document is created at P2P Listener app side.

**Comment by hideki** [comment] 2015-03-12 18:59
From the log message, `onCreate()` of `MainActivity` is called before SQLException was thrown. 

It seems Activity was released by Android system because of memory requirement.

To avoid this, Manager and Database instance should move to Application class.

Log message before Exception was thrown:
```
03-12 11:49:45.991  23823-23823/couchbase.com.myp2p E/MainActivity﹕ onCreate()
03-12 11:49:46.012  23823-23823/couchbase.com.myp2p V/TDCollateJSON﹕ SQLite3 handle is -1404186496
03-12 11:49:46.047  23823-23823/couchbase.com.myp2p V/TDCollateJSON﹕ SQLite3 handle is -1404186496
03-12 11:49:46.089  23823-23901/couchbase.com.myp2p E/SQLiteLog﹕ (539) recovered 2 pages from /data/data/couchbase.com.myp2p/files/db.cblite-journal
03-12 11:49:46.091  23823-23901/couchbase.com.myp2p E/SQLiteLog﹕ (1) no such table: attachments
03-12 11:49:46.095  23823-23901/couchbase.com.myp2p E/SQLiteQuery﹕ exception: no such table: attachments (code 1); query: SELECT filename, key, type, length, revpos FROM attachments WHERE sequence=?
03-12 11:49:46.097  23823-23901/couchbase.com.myp2p E/Router﹕ Router unable to route request to do_POST_Document_all_docs
    java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteException: no such table: attachments (code 1)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
            at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
            at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
            at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
            at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
            at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine$SQLiteCursorWrapper.moveToNext(AndroidSQLiteStorageEngine.java:178)
            at com.couchbase.lite.Database.getAttachmentsDictForSequenceWithContent(Database.java:2811)
            at com.couchbase.lite.Database.extraPropertiesForRevision(Database.java:1459)
            at com.couchbase.lite.Database.documentPropertiesFromJSON(Database.java:1560)
            at com.couchbase.lite.Database.getAllDocs(Database.java:2414)
            at com.couchbase.lite.router.Router.do_POST_Document_all_docs(Router.java:976)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.couchbase.lite.router.Router.start(Router.java:472)
            at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
            at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
            at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
            at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
            at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by hideki** [comment] 2015-03-12 19:20
By moving Manager, Database and LiteListener to Application class, I don't see the Exception any more.

**Comment by hideki** [comment] 2015-03-12 19:20
@pasin Could you please read last two my comments? If it is make sense, please close this ticket. Thanks!

**Closed** 2015-03-12 20:20 UTC
Labels: bug, reproduce/investigate
