### ISSUE TITLE
Unique constraint violation in sqlite

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-java-core#655] opened 2015-06-04 13:14 UTC
I saw this exception today. I have the latest dev version: com.couchbase.lite:couchbase-lite-android:1.1.0-532

Is it because of normal replication conflict, or it is a bug?

06-04 15:03:22.968  19524-20849/com.droid4you.application.wallet E/SQLiteDatabase﹕ Error inserting doc_id=29 revid=1-180469feb76af1618ebd52ee2488de92 no_attachments=true deleted=false current=true json=[B@34adc87d
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: revs.doc_id, revs.revid (code 2067)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.newrelic.agent.android.instrumentation.SQLiteInstrumentation.insert(SQLiteInstrumentation.java:115)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:133)
            at com.couchbase.lite.Database.insertRevision(Database.java:3901)
            at com.couchbase.lite.Database.forceInsert(Database.java:4464)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:507)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:101)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:203)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:24)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:41)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by hideki** [comment] 2015-06-04 16:08
Hi @biokys Thank you very much for bug report

revs table record should be unique by doc_id and revid. `UNIQUE (doc_id, revid)`
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Database.java#L184-L192

Some reason, CBL tried to insert revs with `doc_id=29` and `revid=1-180469feb76af1618ebd52ee2488de92` twice.

Potential reasons:
1. CouchDB has duplicated data (I believe you are using CouchDB)
2. CBL requested revs (`doc_id=29` and `revid=1-180469feb76af1618ebd52ee2488de92`) twice

I need some helps from you.
1. Is this 100% reproducible?
2. Could you please check if duplicated revs exists in CouchDB?
3. Could you please try `1.1.0-521`? http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.1.0-521/ 

Explanation for 3). To fix couchbase/couchbase-lite-android/issues/597, I committed https://github.com/couchbase/couchbase-lite-java-core/commit/b9ce9ad08ff0feeff52a7ed24437297dcd27600c . I guess this change might cause disorder  document request during pull-replication. 

Thanks,
Hideki

**Comment by biokys** [comment] 2015-06-04 18:52
I catch more info before exception. It may help you. I can see just one document to be pulled, but two tries to insert revision. 

It happens, if i create document on a remote couchdb through REST API and this remote endpoint is continually replicated with CBL Android. 

06-04 20:45:39.780  20500-20787/com.droid4you.application.wallet D/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@6938889: changeTrackerReceivedChange: {seq=33, id=UserConfigure, changes=[{rev=1-a08a91dbcf664e5e22224e82039e05ee}]}
06-04 20:45:39.780  20500-20787/com.droid4you.application.wallet D/Sync﹕ changeTrackerReceivedChange: {seq=33, id=UserConfigure, changes=[{rev=1-a08a91dbcf664e5e22224e82039e05ee}]}
06-04 20:45:39.780  20500-20787/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@3f45aa06: adding rev to inbox {UserConfigure #1-a08a91dbcf664e5e22224e82039e05ee}
06-04 20:45:39.780  20500-20783/com.droid4you.application.wallet D/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@150dc178: changeTrackerReceivedChange: {seq=33, id=UserConfigure, changes=[{rev=1-a08a91dbcf664e5e22224e82039e05ee}]}
06-04 20:45:39.780  20500-20783/com.droid4you.application.wallet D/Sync﹕ changeTrackerReceivedChange: {seq=33, id=UserConfigure, changes=[{rev=1-a08a91dbcf664e5e22224e82039e05ee}]}
06-04 20:45:39.781  20500-20773/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Status: REPLICATION_IDLE
06-04 20:45:39.782  20500-20773/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Type: PULL
06-04 20:45:39.782  20500-20787/com.droid4you.application.wallet D/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@6938889: /changeTrackerReceivedChange: {seq=33, id=UserConfigure, changes=[{rev=1-a08a91dbcf664e5e22224e82039e05ee}]}
06-04 20:45:39.782  20500-20773/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Change count: 1
06-04 20:45:39.782  20500-20773/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Completed change count: 0
06-04 20:45:39.782  20500-20787/com.droid4you.application.wallet D/Sync﹕ changeTrackerCaughtUp
06-04 20:45:39.782  20500-20773/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ resolveReplicationProgress, current:28, total:29, active:true
06-04 20:45:39.780  20500-20783/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@22916ac9: adding rev to inbox {UserConfigure #1-a08a91dbcf664e5e22224e82039e05ee}
06-04 20:45:39.784  20500-20773/com.droid4you.application.wallet D//Application.java:138﹕ CBLManagerWorkExecutor ReplicationStartedEvent{}
06-04 20:45:39.785  20500-20773/com.droid4you.application.wallet D//Application.java:145﹕ CBLManagerWorkExecutor ReplicationEvent{current=28, total=29, active=true}
06-04 20:45:39.786  20500-20773/com.droid4you.application.wallet D/Sync﹕ processInbox called
06-04 20:45:39.786  20500-20993/com.droid4you.application.wallet D/Sync﹕ [PullerInternal.waitForPendingFutures()] STARTED - thread id: 93674
06-04 20:45:39.789  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Status: REPLICATION_IDLE
06-04 20:45:39.789  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Type: PULL
06-04 20:45:39.789  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Change count: 1
06-04 20:45:39.789  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Completed change count: 0
06-04 20:45:39.789  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ resolveReplicationProgress, current:0, total:1, active:true
06-04 20:45:39.790  20500-20542/com.droid4you.application.wallet D//Application.java:138﹕ CBLManagerWorkExecutor ReplicationStartedEvent{}
06-04 20:45:39.795  20500-20542/com.droid4you.application.wallet D//Application.java:145﹕ CBLManagerWorkExecutor ReplicationEvent{current=0, total=1, active=true}
06-04 20:45:39.795  20500-20773/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@3f45aa06: pullRemoteRevision with rev: {UserConfigure #1-a08a91dbcf664e5e22224e82039e05ee}
06-04 20:45:39.795  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: ReplicationStartedEvent{}
06-04 20:45:39.797  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: ReplicationEvent{current=28, total=29, active=true}
06-04 20:45:39.797  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: com.squareup.otto.DeadEvent@1c02b1e9
06-04 20:45:39.800  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: ReplicationStartedEvent{}
06-04 20:45:39.800  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: ReplicationEvent{current=0, total=1, active=true}
06-04 20:45:39.802  20500-20542/com.droid4you.application.wallet D/Sync﹕ processInbox called
06-04 20:45:39.802  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: com.squareup.otto.DeadEvent@2e1837a
06-04 20:45:39.806  20500-20783/com.droid4you.application.wallet D/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@150dc178: /changeTrackerReceivedChange: {seq=33, id=UserConfigure, changes=[{rev=1-a08a91dbcf664e5e22224e82039e05ee}]}
06-04 20:45:39.806  20500-20783/com.droid4you.application.wallet D/Sync﹕ changeTrackerCaughtUp
06-04 20:45:39.808  20500-20542/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@22916ac9: pullRemoteRevision with rev: {UserConfigure #1-a08a91dbcf664e5e22224e82039e05ee}
06-04 20:45:39.813  20500-20542/com.droid4you.application.wallet D/Sync﹕ [fireTrigger()] => RESUME
06-04 20:45:39.819  20500-20542/com.droid4you.application.wallet D/Sync﹕ firing trigger: RESUME
06-04 20:45:39.820  20500-20999/com.droid4you.application.wallet D/Sync﹕ [PullerInternal.waitForPendingFutures()] STARTED - thread id: 93677
06-04 20:45:39.820  20500-20542/com.droid4you.application.wallet D/Sync﹕ State transition: IDLE -> RUNNING (via RESUME).  this: com.couchbase.lite.replicator.PullerInternal@22916ac9
06-04 20:45:39.820  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Status: REPLICATION_ACTIVE
06-04 20:45:39.820  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Type: PULL
06-04 20:45:39.820  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Change count: 1
06-04 20:45:39.820  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ Completed change count: 0
06-04 20:45:39.820  20500-20542/com.droid4you.application.wallet D/YablohnCouchDbProvider﹕ resolveReplicationProgress, current:0, total:1, active:true
06-04 20:45:39.821  20500-20542/com.droid4you.application.wallet D//Application.java:145﹕ CBLManagerWorkExecutor ReplicationEvent{current=0, total=1, active=true}
06-04 20:45:39.826  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: ReplicationEvent{current=0, total=1, active=true}
06-04 20:45:39.826  20500-20500/com.droid4you.application.wallet D//OttoBus.java:43﹕ main Posting event: com.squareup.otto.DeadEvent@f7825d
06-04 20:45:39.901  20500-20909/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.support.RemoteRequestRetry$1@16a680a3: RemoteRequestRetry inner request finished, url: https://xxx:6984/wallet-84277131-dad7-4565-8379-e70c5972a778/UserConfigure?rev=1-a08a91dbcf664e5e22224e82039e05ee&revs=true&attachments=true
06-04 20:45:39.902  20500-20909/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.support.RemoteRequestRetry$1@16a680a3: RemoteRequestRetry was successful, calling callback url: https://xxx:6984/wallet-84277131-dad7-4565-8379-e70c5972a778/UserConfigure?rev=1-a08a91dbcf664e5e22224e82039e05ee&revs=true&attachments=true
06-04 20:45:39.902  20500-20909/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@3f45aa06: pullRemoteRevision add rev: {UserConfigure #1-a08a91dbcf664e5e22224e82039e05ee} to batcher: com.couchbase.lite.support.Batcher@1289fa0
06-04 20:45:39.916  20500-20903/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.support.RemoteRequestRetry$1@cbcf1e: RemoteRequestRetry inner request finished, url: https://xxx:6984/wallet-84277131-dad7-4565-8379-e70c5972a778/UserConfigure?rev=1-a08a91dbcf664e5e22224e82039e05ee&revs=true&attachments=true
06-04 20:45:39.916  20500-20903/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.support.RemoteRequestRetry$1@cbcf1e: RemoteRequestRetry was successful, calling callback url: https://xxx:6984/wallet-84277131-dad7-4565-8379-e70c5972a778/UserConfigure?rev=1-a08a91dbcf664e5e22224e82039e05ee&revs=true&attachments=true
06-04 20:45:39.917  20500-20903/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@22916ac9: pullRemoteRevision add rev: {UserConfigure #1-a08a91dbcf664e5e22224e82039e05ee} to batcher: com.couchbase.lite.support.Batcher@3f1683ff
06-04 20:45:40.301  20500-20993/com.droid4you.application.wallet D/Sync﹕ batcher.waitForPendingFutures()
06-04 20:45:40.301  20500-20993/com.droid4you.application.wallet D/Sync﹕ waitPendingFuturesCompleted()
06-04 20:45:40.320  20500-20999/com.droid4you.application.wallet D/Sync﹕ batcher.waitForPendingFutures()
06-04 20:45:40.320  20500-20999/com.droid4you.application.wallet D/Sync﹕ waitPendingFuturesCompleted()
06-04 20:45:40.904  20500-20773/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@3f45aa06 inserting 1 revisions...
06-04 20:45:40.917  20500-20542/com.droid4you.application.wallet D/Sync﹕ com.couchbase.lite.replicator.PullerInternal@22916ac9 inserting 1 revisions...
06-04 20:45:40.940  20500-20542/com.droid4you.application.wallet E/SQLiteLog﹕ (2067) abort at 37 in [INSERT INTO revs(doc_id,revid,no_attachments,deleted,current,json) VALUES (?,?,?,?,?,?)]: UNIQUE constraint failed: revs.doc_id, revs.revid
06-04 20:45:40.946  20500-20542/com.droid4you.application.wallet E/SQLiteDatabase﹕ Error inserting doc_id=29 revid=1-a08a91dbcf664e5e22224e82039e05ee no_attachments=true deleted=false current=true json=[B@3e61bf2a
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: revs.doc_id, revs.revid (code 2067)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.newrelic.agent.android.instrumentation.SQLiteInstrumentation.insert(SQLiteInstrumentation.java:115)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:133)
            at com.couchbase.lite.Database.insertRevision(Database.java:3901)
            at com.couchbase.lite.Database.forceInsert(Database.java:4464)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:507)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:101)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:203)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:24)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:41)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by biokys** [comment] 2015-06-04 18:56
Downgrade to 1.1.0-521 didn't help!

**Comment by biokys** [comment] 2015-06-04 19:16
Hey, I slowly went down through versions and it seems, problem was brought in version 1.1.0-513, older version 0.0.0-512 was working well in this situation. Hope it helps!

**Comment by hideki** [comment] 2015-06-08 23:31
Hi @biokys,

Sorry for not responding for a while.

Thank you for additional information.

I checked commits between 1.1.0-513 and 1.1.0-512, but non of commits should not affect. And I tried to reproduce this issue with creating document on CouchDB by REST API. But it also does not reproduce the problem.

As you wrote in previous comment, ChangeTracker added the change twice for same document and revision. I will look into the issue from this point.

**Comment by hideki** [comment] 2015-06-09 05:32
Hi @biokys,

I am still not able to reproduce this issue. Do you know exact steps to reproduce this issue?

**Comment by hideki** [comment] 2015-06-09 05:58
Note to Self:

* From the linked code, pull replicator does not fetch revisions which are already in the database. This code indicates SG or CouchDB returns changes for revisions that already exist in local database. And, if `_changes` returns duplicated change, client code should ignore second change.
https://github.com/couchbase/couchbase-lite-java-core/blob/61d021408a952140fb30194a6d1bfe93d4f9f46d/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L163

* Does checking conflict solve this issue? iOS version does, but Android does not.
https://github.com/couchbase/couchbase-lite-ios/blob/4cc63fde38bb213f251380da1cc7c58e75d0e0ba/Source/CBL_Puller.m#L241
https://github.com/couchbase/couchbase-lite-ios/blob/4cc63fde38bb213f251380da1cc7c58e75d0e0ba/Source/CBL_Puller.m#L330

**Comment by biokys** [comment] 2015-06-09 09:28
@hideki: i am enclosing json object i stored through rest api in couchdb:

{
   "_id": "UserConfigure",
   "_rev": "1-aa61d46b6569e0caeb0651f118f4c941",
   "deviceId": "backend",
   "key": "user_object",
   "value": "1433750673970",
   "reservedCreatedAt": "2015-06-08T08:04:33.970Z",
   "reservedModelType": "UserConfigure",
   "reservedOwnerId": "6269f6f6-78e9-44a5-a663-f3e48eb2cadd",
   "reservedSource": "backend",
   "changeSource": 2,
   "changeType": 1
}

**Comment by hideki** [comment] 2015-06-09 17:41
Hi @biokys,
Thank you for JSON doc. But I still could not reproduce the issue.

Following is steps I tried to reproduce:
1. Running CouchDB 1.6.1 on local (OSX)
2. Created Database on CouchDB. name => test
3. Run simple android app with continuous pull replication
4. Create doc using REST API
```
curl -X PUT -H "Content-Type: application/json" -d '{
   "deviceId": "backend",
   "key": "user_object",
   "value": "1433750673970",
   "reservedCreatedAt": "2015-06-08T08:04:33.970Z",
   "reservedModelType": "UserConfigure",
   "reservedOwnerId": "6269f6f6-78e9-44a5-a663-f3e48eb2cadd",
   "reservedSource": "backend",
   "changeSource": 2,
   "changeType": 1
}' http://localhost:5984/test/UserConfigure
```

Results: At Android side, any Exception were not thrown.

Question: Is it correct steps to reproduce the problem??? Please let us know!

**Comment by biokys** [comment] 2015-06-11 07:15
Yes i think it is correct steps. I am not sure why i facing this problem. Meanwhile I made a workaround so it is not problem for me right now.

**Comment by hideki** [comment] 2015-06-11 08:26
@biokys  Thank you for your comment. I believe something is missing to reproduce this issue now. I will keep eye open for this problem.

**Comment by bundeeteddee** [comment] 2015-06-29 13:38
@biokys , is it possible to disclose what workaround you did? I'm also facing the same issue at the moment.

@hideki , my error log looks like this:
```
E/SQLiteLog﹕ (2067) abort at 37 in [INSERT INTO revs(doc_id,revid,no_attachments,deleted,current,json) VALUES (?,?,?,?,?,?)]: UNIQUE constraint failed: revs.doc_id, revs.revid
E/SQLiteDatabase﹕ Error inserting doc_id=23089 revid=1-75c8b377dbb6216440ea6738a146d6ae no_attachments=true deleted=false current=true json=[B@307f9acf
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: revs.doc_id, revs.revid (code 2067)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:952)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1609)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1479)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:133)
            at com.couchbase.lite.Database.insertRevision(Database.java:3901)
            at com.couchbase.lite.Database.forceInsert(Database.java:4464)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:507)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:101)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:205)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:24)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:41)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

I was doing an initial non-continuous sync with a couch db, containing ~83k documents, with update sequence of 82712. It synced roughly about 20k documents before i see that log. I attached a Replicatio.ChangeListener to the pull replicator and at that point onwards i see errors coming in.

```
/**
     * Observer for replication errors
     */
    public static class ReplicationErrorObserver implements Replication.ChangeListener {
        private CountDownLatch doneSignal;

        public ReplicationErrorObserver(CountDownLatch doneSignal) {
            this.doneSignal = doneSignal;
        }

        @Override
        public void changed(Replication.ChangeEvent event) {
            Replication replicator = event.getSource();
            if (replicator.getLastError() != null) {
                doneSignal.countDown();

                KLog.e(TAG, "ReplicationErrorObserver >>> " + replicator.getLastError().getLocalizedMessage() + " " + replicator.getLastError().toString(), Severity.WTF);

                //Only force exit if this is due to unauthorized problem
                if(replicator.getLastError().getLocalizedMessage() != null && replicator.getLastError().getLocalizedMessage().equalsIgnoreCase("Unauthorized")){
                    //Check that if we have already dealt with this situation
                    if(KlinifyApplication.getInstance().isAppInitialized()){
                        //Deal with it
                        KlinifyApplication.getInstance().pushRestartApplicationEvent("Unauthorized access to database replication. Please check with administrator.");
                    }
                }
            }
        }
    }
```

The error seems to be from HttpResponseException. Maybe somewhere in the middle my device got disconnected and reconnected to the network and it triggered this.

**Comment by hideki** [comment] 2015-06-30 02:52
Hi @bundeeteddee, thank you for your inputs.

**Comment by hideki** [comment] 2015-09-25 22:21
In the CBL iOS, if SQL error is SQLITE_CONSTRAINT, the method does not exit. We needs to port this error handling to Android/Java.
https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBL_SQLiteStorage.m#L1668-L1684

In addition to this, it is time to fix the following codes too. 
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L1287-L1308

**Closed** 2015-09-28 21:12 UTC
Labels: bug, in progress, needsmoreinfo, P3: low, S3: major, size-large

**Comment by atom992** [comment] 2015-12-07 12:51
Hi,@hideki 
  for the code:
```
/**
     * Observer for replication errors
     */
    public static class ReplicationErrorObserver implements Replication.ChangeListener {
        private CountDownLatch doneSignal;

        public ReplicationErrorObserver(CountDownLatch doneSignal) {
            this.doneSignal = doneSignal;
        }

        @Override
        public void changed(Replication.ChangeEvent event) {
            Replication replicator = event.getSource();
            if (replicator.getLastError() != null) {
                doneSignal.countDown();

                KLog.e(TAG, "ReplicationErrorObserver >>> " + replicator.getLastError().getLocalizedMessage() + " " + replicator.getLastError().toString(), Severity.WTF);

                //Only force exit if this is due to unauthorized problem
                if(replicator.getLastError().getLocalizedMessage() != null && replicator.getLastError().getLocalizedMessage().equalsIgnoreCase("Unauthorized")){
                    //Check that if we have already dealt with this situation
                    if(KlinifyApplication.getInstance().isAppInitialized()){
                        //Deal with it
                        KlinifyApplication.getInstance().pushRestartApplicationEvent("Unauthorized access to database replication. Please check with administrator.");
                    }
                }
            }
        }
    }
```

when will cause Unauthorized error?
I found the same error:
```
V/Sync    ( 2739): com.couchbase.lite.replicator.BulkDownloader[/jarvis/_bulk_get]: BulkDownloader finally block.  url: http://10.0.3.2/sgdb/_bulk_get?revs=true&attachments=true
V/Sync    ( 2739): com.couchbase.lite.replicator.BulkDownloader[/jarvis/_bulk_get]: BulkDownloader calling respondWithResult.  url: http://10.0.3.2/sgdb/_bulk_get?revs=true&attachments=true, error: org.apache.http.client.HttpResponseException: Unauthorized
E/Sync    ( 2739): com.couchbase.lite.replicator.PullerInternal@307ee6af: Progress: set error = org.apache.http.client.HttpResponseException: Unauthorized
```
but I don't know why I got Unauthorized Exception. This cause the Replication only sync the part of data.

**Comment by hideki** [comment] 2015-12-07 23:47
@atom992 
`Unauthorized Exception` is usually caused by authentication error. Please check your Sync Gateway or CouchDB settings.

**Comment by atom992** [comment] 2015-12-08 02:30
Thanks, I fixed the issue. It do caused by authentication error.
