### ISSUE TITLE
Sync (pull replication) fails on document with a lot of revisions with conflicts and attachments

### ISSUE THREAD

**Issue by jcamp1** [couchbase/couchbase-lite-java-core#415] opened 2015-02-06 22:31 UTC
Greetings,
We have a document that has an insanely large amount of revisions on it and because of that I'm getting the following error during sync:
<code>
02-06 05:19:40.423    3163-3200/com.app.test E/Sync﹕ Error pulling remote revision
    org.apache.http.client.HttpResponseException: Request-URI Too Large
            at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:77)
            at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:46)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
</code>

The request in question is:
<code>
02-06 05:19:40.423 D/Sync﹕ com.couchbase.lite.support.RemoteRequestRetry$1@34a1027b: RemoteRequestRetry inner request finished, url: https://xxxgatewayurlxxx/c91aabd3-d7e6-465d-adc9-2606604c5ee2?rev=1254-79ba75539b790496054bb76a4f354224&revs=true&attachments=true&atts_since=%5B%221183-5d5e48f4ddc18840f981eff435a0e966%22%2C%22876-f2d7ed90282bef2c89c745c4cf25c1b5%22%2C%221054-325abf46f13d17e1c5575de171958e3d%22%2C%221527-a2d9e4097bc2a011367ae4b8922d0c3c%22%2C%22302-2ab414aadc51cc80b980ef0110fcfd7a%22%2C%223270-1a85a48a1756777fcd6dbcf3fbaea27c%22%2C%22325-3619e1daf7c7c79261699bc75f5b7ac1%22%2C%223794-3639b41959012c43656dde0bb95f45de%22%2C%22777-4d7c216bc6639193a5809af3de7c9db6%22%2C%22441-b94af1a31f3bca46c1ec16aef5cf5e58%22%2C%221569-62b281fb95fd3917ac4cb71ae5fbcc1d%22%2C%22743-4bbf7c4b132a5b1ee59118f1e410c8be%22%2C%221966-83bdad2629689c1c8022e0a17f4b2733%22%2C%22708-3f07d83331a640c80d140c2cbbb62aeb%22%2C%22798-d37b0ef12b6b4194393448b8fac14bb6%22%2C%222796-e3068a08c66ec13e130fbcd030618d34%22%2C%224365-3b4438ca0b68f55bc2894ac1f1616a19%22%2C%22872-ce03b0f4179d9d2f43980f3f47d7fa2e%22%2C%22236-9d6dfc201dfb3f2de2c5b3e37789cb73%22%2C%22860-59127ae8e524f595cc5c5309df67fa33%22%2C%22602-84822ff873967bf2873db7cf8fcf635c%22%2C%22904-9a46e1a2595ef290a7b0e75349695337%22%2C%223660-8a3f50abd0ef2047dc505bcf490f896c%22%2C%22703-9673f62c3d5fdac41e9ee91c6b8ba237%22%2C%22645-a707052940aba842112fa85f056e5ae8%22%2C%22275-69975e7807ad68ffcb1970f7cb8cfc93%22%2C%22736-f9ea0d35d458710477ff355c85a11e18%22%2C%221106-f7c413393c78248283611cbc734d2a5d%22%2C%22335-6c57285ae06a03f4637f46cb1f13bad8%22%2C%221404-a398501b37eac4028b64e7fe8b2e85ff%22%2C%22871-48b9bb0f5328b3798086a5b6fee1b510%22%2C%221160-f07a3c2c42ae24a930c83cb7c733dd10%22%2C%221686-bbb6998ed0abca8851d6eee787465ecc%22%2C%221234-ed79304e4582631f1043319abaf7f210%22%2C%221307-16423b22132b4090f5fce403f04ea8f8%22%2C%222022-19cbd866e71906915dd6df03601c4653%22%2C%222001-3709d20b474a1edf8e85d8650d8ff196%22%2C%222615-764799de6606b3885997e7ecb64b8912%22%2C%221641-36b2c8398ca3bd769f645ce37b398b14%22%2C%22813-5591e82882472dbb670fa90b1c27b4db%22%2C%22813-7b050e3c2a5d6f358ba290e0a086b2d7%22%2C%221992-225fa64a6a755ce6b848585e0c705510%22%2C%223648-2dda93314aeefe8b884de8f47619015c%22%2C%221340-3e9efe5cb612e8a9da582f73aa85a02b%22%2C%221257-f717653552140eb48c1b60be29680160%22%2C%221635-983703808b0c64030c120dfbce36c0e4%22%2C%22907-141235442235a2f866b20258d0f43289%22%2C%22614-fae639f0915fcbdace025efedb159440%22%2C%221715-adade5fef13421fdb1950ac2a26a4f3f%22%2C%224004-98ddb51edf086bd7b17b90d84daaa153%22%2C%22771-8ce0bae3f019727a50d9dd506a9ffa72%22%2C%221204-68ef2c0c932132919c6909ad66500dee%22%2C%221839-3c5193895c0a2c651dfe308d17eb8922%22%2C%221840-bd4e97da64ce7e2cd5d1334126352d52%22%2C%22622-6dcb09e697e8f5d079810ec5204e794b%22%2C%22300-37857104e38dff559fb68e77ece7db00%22%2C%222892-52faab02bf26283e0dd8905f2657ba21%22%2C%221635-ceed67e8485e96a679e12d92dd0ffe80%22%2C%221576-13082f24b471a4e97f937ee310f80bec%22%2C%222895-5a13d2c24471305e5572f6b74be676bb%22%2C%221226-ea2929e0b49240bafb1bd154801b8c53%22%2C%221235-77b299d6e44e9602c6aef2a2d4af4094%22%2C%22535-30b22015556e532f59a527490ccec612%22%2C%222848-2abc92dc45cda1bcd3e17862c96df372%22%2C%221662-328eb4525aa84232fc883550f2f435bb%22%2C%221636-0567d383e67516b45498b2b87d25e447%22%2C%22989-0fe38147a67f9b95d7b1bde1e8165935%22%2C%221828-93a548a7edbd1eec3e0f054b45198e1b%22%2C%22263-14387f0734f1b442281ebe1af48c2fce%22%2C%22298-b6b643404fca0ab4948979f35d603d12%22%2C%221228-9ad1825017b6c094eb9236eb85c82091%22%2C%222030-56468ae6a2b22a6cc39fb54cac86a7e5%22%2C%221181-0e30c249bbf2d66866fa763617312f63%22%2C%221379-ab20c029d74c94fcbec94607b766576e%22%2C%221494-dcc84c84d70ae205b5c62809d6ea1d24%22%2C%22217-53740e6b5ad1395c3bda785ed58d8f65%22%2C%221481-ff66b523f19edddd2c2aeaba79739632%22%2C%22333-a65c80e98408d7b95f021418c01cc907%22%2C%221260-34dd9e3b571f75a7198109e1430b43a2%22%2C%222032-41c989b807a73089684df72c8615730c%22%2C%221331-d60e8678c53c5b9db122ae75e0b8fe8f%22%2C%221731-259bb12b376dfaf97750a40cd0e6c976%22%2C%221344-5e7d72188ce111fe65cfbfac9ad76dad%22%2...(logcat truncated the rest)
</code>

Now, I understand that we don't want to update documents -we want to create new document revisions, and we've moved to that model, but we need this data for historical purposes and the iOS CBL framework seems to work just fine with this document. Is there a fix we could get for this issue or do you have any recommendations on a workaround? I'm wondering if maybe the iOS framework doesn't append the atts_since= argument to the url or truncates (or otherwise handles) the argument if it grows to large?

Thanks!
Justin

**Comment by hideki** [comment] 2015-02-06 23:00
@jcamp1 Thank you for bug report.

Some questions
- How many revisions does cause this issue? >100? >1K? 
- It seems pull replicator cause this issue. is it correct?
- It seems doc includes attachment. How is size? and how many?
- Can you provide flow that cause this ?

**Comment by jcamp1** [comment] 2015-02-06 23:31
Hi Hideki,
Here's the rev on this particular document:
"_rev":"4365-3b4438ca0b68f55bc2894ac1f1616a19"

I'm not sure it's specifically quantifiable in terms of revisions on a document. What's happening is I'm starting a pull replication from a cleanly installed client, so it's syncing all documents. This particular document has so many revisions that the request URL is too large for a GET request and the server is refusing it.

This app is just a prototype so it's very simple. Basically I'm just doing this:
<code>
protected static Manager manager  = new Manager(new AndroidContext(this), Manager.DEFAULT_OPTIONS);
private Database database = manager.getDatabase("testdb");
URL syncUrl;
        try {
            syncUrl = new URL("https://cbltestsyncws.sightplan.com:8443/sync_gateway_sw1");
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
        logger.d("Starting Replication");
        Replication pullReplication = database.createPullReplication(syncUrl);
        pullReplication.setAuthenticator(new BasicAuthenticator(username, password));
        pullReplication.setContinuous(true);
        //pullReplication.setChannels(Arrays.asList("system"));
        pullReplication.start();
        pullReplication.addChangeListener(this);
</code>

The latest revision of the doc only has one attachment but I'm pretty sure there's attachments on most revisions... the whole document is huge, somewhere in the 10-15meg range in total (due to the revisions).

**Comment by hideki** [comment] 2015-02-06 23:59
CBL iOS limits number of revisions.
https://github.com/couchbase/couchbase-lite-ios/blob/dd20d33b4bc759bd76e3c84d0ed6e5dfbe313819/Source/CBL_Puller.m#L407-L416 

But CBL Android (Java Core) does not implement this. Need to port code from iOS.
https://github.com/couchbase/couchbase-lite-java-core/blob/c59086252fa30c4cb77eca62f60577b61c88f1cb/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L583-L596

**Comment by hideki** [comment] 2015-02-07 00:12
@jcamp1 

Thank you for additional comment.

> What's happening is I'm starting a pull replication from a cleanly installed client, so it's syncing all documents.

The client should have document in database with some revisions to generates this GET request. I think it requires some other steps to cause this. For example, other device update this document, etc. If possible, could you please provide further detailed steps to reproduce this issue?

Note: CBL iOS has code to limit revision history. This is reason that iOS version does not have this issue.

Thanks,
Hideki

**Comment by jcamp1** [comment] 2015-02-07 04:59
Is there any ETA on the porting of that specific code? It sounds like that is exactly the fix I need :)

**Comment by jcamp1** [comment] 2015-02-07 05:02
I believe the quickest way to reproduce this is to create a script that updates a document around 4000 times. That sounds ridiculous but it's accurate. If you create a document, then update it (don't create new documents but actually update the same document) about 4000 times, you'll get a document with tons of revisions. Then try to sync it :)

**Comment by hideki** [comment] 2015-02-07 05:20
@jcamp1 If limiting revisions could solve your issue, it does not take many days. We could try to fix this during next week, and could push it to master or branch.

**Comment by jcamp1** [comment] 2015-02-08 16:10
I am very confident it would solve my issue. Pushing a fix to master would be fantastic! Much appreciated!

**Comment by hideki** [comment] 2015-02-10 20:49
Hi @jcamp1 

I need your input. What version of Couchbase Lite for Android are you using?

I am not able to reproduce the issue you are encountering. Reason is described below.
 
In current master branch, `atts_since` parameter is generated by calling `knownCurrentRevIDs(rev)` in `pullRemoteRevision(final RevisionInternal rev)`. 
https://github.com/couchbase/couchbase-lite-java-core/blob/36724f7febb79e29a7b1ad5bb887bca9ca975bf7/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L587

In `knownCurrentRevIDs()`, calling `Database.getAllRevisionsOfDocumentID(String docId, boolean onlyCurrent)` with second parameter `true`. So It should return only one Revision object.

`List<String> knownCurrentRevIDs(RevisionInternal rev)`
https://github.com/couchbase/couchbase-lite-java-core/blob/36724f7febb79e29a7b1ad5bb887bca9ca975bf7/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L645

`Database.getAllRevisionsOfDocumentID(String docId, boolean onlyCurrent)`
https://github.com/couchbase/couchbase-lite-java-core/blob/36724f7febb79e29a7b1ad5bb887bca9ca975bf7/src/main/java/com/couchbase/lite/Database.java#L1698 

`Database.getAllRevisionsOfDocumentID(String docId, long docNumericID, boolean onlyCurrent)`
https://github.com/couchbase/couchbase-lite-java-core/blob/36724f7febb79e29a7b1ad5bb887bca9ca975bf7/src/main/java/com/couchbase/lite/Database.java#L1655

If multiple records have `current` field of `revs` table true(1) per same doc_id, it might cause the problem you are encountering.

**Comment by jcamp1** [comment] 2015-02-11 15:49
Hi @hideki,

I'm working with the master branch code.
I just confirmed that your suspicion was correct, the document in question has many conflicts. Following your links I was able to print out a list of revisions it's trying to include in the atts_since argument (the list is far to long to include here).

So I'm guessing that the atts_since argument must be limited to some hard limit? How does the iOS client handle this issue?

Thanks!
Justin

**Comment by jcamp1** [comment] 2015-02-11 21:47
Hi @hideki,

I did a quick test against the new branch you created and that did indeed solve the problem I was seeing. I found a separate issue which I'll open a separate ticket for, but this one appears to be fixed.

Many thanks!

**Comment by hideki** [comment] 2015-02-11 22:48
hi @jcamp1
Is #422 reproducible with master branch? or does it occurs with development branch for this issue?

**Comment by jcamp1** [comment] 2015-02-11 23:26
hi @hideki,

My apologies, that was on the feature branch. I changed over to master and everything appears to be working correctly.

Thanks!

**Comment by hideki** [comment] 2015-02-11 23:34
@jcamp1 I wonder if the fix for this issue might cause side effect. I fixed one issue after you filed #422. I hope it also solved new issue you reported. Could you please retest with the latest commit of feature branch again? 

status: currently PR for this is middle of code review process.

Thanks you for your contribution!

**Comment by jcamp1** [comment] 2015-02-12 15:35
Hi @hideki,

I'd be happy to test. Which branch should I test on? The branch you opened for this issue seems to be no longer available.

Thanks,
Justin

**Comment by hideki** [comment] 2015-02-12 15:46
Hi @jcamp1,

Could you please use the branch that has fix for this issue.  https://github.com/couchbase/couchbase-lite-java-core/tree/feature/issue_415_pull_many_revs_attr

**Comment by jcamp1** [comment] 2015-02-12 16:58
On the test branch I'm getting the following (which I reported in #422)
```
02-12 11:56:48.945    2297-2322/com.sightplan.residentapptest E/SQLiteLog﹕ (1299) abort at 11 in [INSERT INTO attachments(type,sequence,revpos,filename) VALUES (?,?,?,?)]: NOT NULL constraint failed: attachments.key
02-12 11:56:48.946    2297-2322/com.sightplan.residentapptest E/SQLiteDatabase﹕ Error inserting type=image/jpeg sequence=14178 revpos=27 filename=siteImage
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: attachments.key (code 1299)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
            at com.couchbase.lite.android.AndroidSQLiteStorageEngine.insert(AndroidSQLiteStorageEngine.java:116)
            at com.couchbase.lite.Database.insertAttachmentForSequenceWithNameAndType(Database.java:2543)
            at com.couchbase.lite.Database.insertAttachmentForSequence(Database.java:2500)
            at com.couchbase.lite.Database.processAttachmentsForRevision(Database.java:3030)
            at com.couchbase.lite.Database.forceInsert(Database.java:4031)
            at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:509)
            at com.couchbase.lite.replicator.PullerInternal$1.process(PullerInternal.java:95)
            at com.couchbase.lite.support.Batcher.processNow(Batcher.java:221)
            at com.couchbase.lite.support.Batcher.access$100(Batcher.java:23)
            at com.couchbase.lite.support.Batcher$1.run(Batcher.java:44)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
02-12 11:56:48.946    2297-2322/com.sightplan.residentapptest E/CBLite﹕ Insert attachment failed (returned -1)
```

**Comment by hideki** [comment] 2015-02-12 17:55
@jcamp1 Thank you for testing. I will investigate this INSERT issue. If you have additional log message, please post on #422.

**Comment by jcamp1** [comment] 2015-02-12 17:56
I'm happy to help. The log messages are very long, so if there's anything specific I can help out with please let me know.

**Comment by hideki** [comment] 2015-02-12 17:58
Posting the log message on [gist](https://gist.github.com/) is ideal.

**Closed** 2015-02-12 18:10 UTC
