### ISSUE TITLE
CBForest: Forestdb Handle is being used by another thread in p2p replication

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1497] opened 2016-10-21 23:24 UTC
Using `Android 1.3.1-62 Google Nexus 6 API 23 Genymotion` with `Mono .NET 1.4.0-49`. Both are using ForestDB https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/listener/shared/client_client/test_peer_2_peer_sanity.py#L164 fails with the following adb output

```
10-21 19:20:11.207  7374  7395 V Database: PUT _id=test_ls_db1_115, _rev=null (allowConflict=false)
10-21 19:20:11.208  7374  7408 E CBForest: Forestdb Handle is being used by another thread 
Forestdb Handle is being used by another thread (-39)
10-21 19:20:11.209  7374  7408 E Database: Error in getAllDocs()
10-21 19:20:11.209  7374  7408 E Database: com.couchbase.cbforest.ForestException: Forestdb Handle is being used by another thread
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.cbforest.DocumentIterator.next(Native Method)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.cbforest.DocumentIterator.next(DocumentIterator.java:40)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.cbforest.DocumentIterator.nextDocument(DocumentIterator.java:58)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.lite.store.ForestDBStore.getAllDocs(ForestDBStore.java:666)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.lite.Database.getAllDocs(Database.java:1644)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.lite.router.Router.do_POST_Document_all_docs(Router.java:1196)
10-21 19:20:11.209  7374  7408 E Database:  at java.lang.reflect.Method.invoke(Native Method)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.lite.router.Router.start(Router.java:555)
10-21 19:20:11.209  7374  7408 E Database:  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
10-21 19:20:11.209  7374  7408 E Database:  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
10-21 19:20:11.209  7374  7408 E Database:  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
10-21 19:20:11.209  7374  7408 E Database:  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
10-21 19:20:11.209  7374  7408 E Database:  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
10-21 19:20:11.209  7374  7408 E Database:  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
10-21 19:20:11.209  7374  7408 E Database:  at java.lang.Thread.run(Thread.java:818)
10-21 19:20:11.211  7374  7408 W Router  : Router unable to route request to do_POST_Document_all_docs
10-21 19:20:11.211  7374  7408 W Router  : java.lang.reflect.InvocationTargetException
10-21 19:20:11.211  7374  7408 W Router  :  at java.lang.reflect.Method.invoke(Native Method)
10-21 19:20:11.211  7374  7408 W Router  :  at com.couchbase.lite.router.Router.start(Router.java:555)
10-21 19:20:11.211  7374  7408 W Router  :  at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:141)
10-21 19:20:11.211  7374  7408 W Router  :  at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
10-21 19:20:11.211  7374  7408 W Router  :  at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
10-21 19:20:11.211  7374  7408 W Router  :  at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
10-21 19:20:11.211  7374  7408 W Router  :  at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
10-21 19:20:11.211  7374  7408 W Router  :  at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
10-21 19:20:11.211  7374  7408 W Router  :  at java.lang.Thread.run(Thread.java:818)
10-21 19:20:11.211  7374  7408 W Router  : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
10-21 19:20:11.211  7374  7408 W Router  :  at com.couchbase.lite.router.Router.convertCBLQueryRowsToMaps(Router.java:1142)
10-21 19:20:11.211  7374  7408 W Router  :  at com.couchbase.lite.router.Router.do_POST_Document_all_docs(Router.java:1197)
10-21 19:20:11.211  7374  7408 W Router  :  ... 9 more
10-21 19:20:11.212  7374  7408 V Listener: RouterCallbackBlock.onResponseReady() START
10-21 19:20:11.212  7374  7408 V Listener: RouterCallbackBlock.onResponseReady() END
10-21 19:20:11.212  7374  7408 V Listener: CountDownLatch.await() START
```

**Comment by hideki** [comment] 2016-10-21 23:36
@sethrosetter 
ForestDB -39 error is caused by multiple threads access to ForestDB handle concurrently. Usually bug is in the method which is executed from other thread (not captured one). I need to reproduce locally. Can you help me to set up test environment locally?
Thanks!

**Comment by sethrosetter** [comment] 2016-10-22 00:24
@hideki, just ping me and I can help you get setup quickly.

**Comment by hideki** [comment] 2017-02-17 02:00
I believe this issue is fixed with recent bug fixes.

**Closed by hideki** 2017-02-17 02:01 UTC
Labels: bug, forestdb, icebox, P2: medium
