### ISSUE TITLE
1.4-12 ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer')) during doc add

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1549] opened 2017-01-12 21:29 UTC
Test failure - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/52/testReport/testsuites.listener.shared.client_sg/test_replication/test_replication_with_multiple_client_dbs_and_single_sync_gateway_db/

logcat - http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/52/artifact/results/logs/LiteServAndroid-test_replication_with_multiple_client_dbs_and_single_sync_gateway_db-2017-01-12%2012%3A09%3A24.629965.txt

**Comment by hideki** [comment] 2017-01-12 22:05
I run the `test_replication_with_multiple_client_dbs_and_single_sync_gateway_db` on my dev machine. The problem is not reproducible. I have assumed that the issue could be caused by test environment. Can we review it? Especially Genymotion Environment.

Gennymotion Version: 2.8.1
Virtual Device: Custom Phone - 4.4.4 API 19 - 768x1280
Virtual Box Version: 5.0.30
Host machine: OSX El Capitan (version 10.11.6)

**Comment by hideki** [comment] 2017-01-12 22:24
Note: 
- Should use Use API 16 to reproduce this issue.

**Comment by hideki** [comment] 2017-01-14 01:13
With 1.4-18, the issue is no longer reproducible. I will close this.

Ref: http://uberjenkins.sc.couchbase.com/job/android-listener-client-sync-gateway/53/

**Closed** 2017-01-14 01:13 UTC
Labels: bug, P1: high
