### ISSUE TITLE
PhoneGap Couchbase Lite View performance issue on Android

### ISSUE THREAD

**Issue by zebra1024** [couchbase/couchbase-lite-java-core#478] opened 2015-03-11 03:43 UTC
We are creating a disconnected app using Cordova,the Phonegap plugin, Sync Gateway, and Couchbase. The sync works fine and pulls down about 8K objects. We then have a number of views using Javascript maps. When we access the views the data is returned as expected. The issue is that this works very fast on iOS and extremely slow on Android - both in the emulator and on physical devices (tested on GS3 & GS5). One view takes a few seconds on iOS and 3 minutes on Android. Other views take upwards of 20 minutes. It seems the index is being created because the 2nd time accessing the view is much faster.

Are there any known issues with Couchbase Lite on Android that would cause this drastic performance gap? We reduced the view map functions to almost nothing and it did not seem to impact the time.

Version: CBL 4.0.2

Map:
```
Example map is as follows
        var userMap = {
            _id: "_design/Users",
            views: {
                byName: {
                    map: function (doc) {
                        if (doc.ObjectType === "User") {
                            emit(doc.Username);
                        }
                    }.toString()
               }
            }
        };
```
I ran this on the emulator and it took about 7 minutes to generate the index (logging below). It ran almost instantaneously on iOS.

03-10 10:53:59.585 V/View ( 2217): Re-indexing view: Users/byName
03-10 11:00:42.251 V/View ( 2217): Finished re-indexing view: Users/byName up to sequence 8196 (deleted 0 added ?)

Example Object:
```
{
   "channels":[
      "1c749055269f4dcb9ccffa6d1c1c153d"
   ],
   "CCObject":"{\"Username\":\"Ted Jones\",\"Password\":\"gR2H5Xv/C8k=\",\"Email\":null,\"AccountIDs\":[\"3ad73f94bb2342889d27fc687d197f87\"],\"Channel\":\"1c749055269f4dcb9ccffa6d1c1c153d\",\"ID\":\"77f39c10e6f3458eb753f37322e96813\",\"RecordVersion\":\"0000000000022615\",\"Type\":\"User\",\"Status\":\"Unchanged\",\"ObjectKey\":\"1c749055269f4dcb9ccffa6d1c1c153d_User_77f39c10e6f3458eb753f37322e96813\"}",
   "Username":"John Lawson",
   "ObjectType":"User",
   "Status":"Unchanged"
}
```

**Comment by hideki** [comment] 2015-03-11 05:49
Originally reported on Couchbase Forum
https://forums.couchbase.com/t/phonegap-couchbase-lite-view-performance-issue-on-android/3156/3

**Comment by hideki** [comment] 2015-03-14 05:15
Index update performance measurement result  => https://github.com/couchbase/couchbase-lite-java-core/issues/491#issuecomment-79863629

**Comment by hideki** [comment] 2015-03-20 20:13
Ticket for Rhino upgrade #512

**Comment by hideki** [comment] 2015-03-20 20:15
By fix of #502,  couchbase-lite-android 's View.updateIndex() performance improved dramatically .  For 10K docs, improved from 9sec to 5sec.

**Comment by zebra1024** [comment] 2015-03-27 03:20
I see that some work has been done on this issue. Is there someplace I can get a build which includes this fix?

**Comment by hideki** [comment] 2015-03-27 05:24
Hi @zebra1024,

We improved View.updateIndex() performance. If your document does not contain non-ASCII characters a lot, current master branch version improve the performance.

If you don't mind to install test version of PhoneGapPlugin manually, please try following steps.

Please follow steps to update PhoneGap plugin:
```
1. Download PhoneGapPlugin and Extract
http://cbfs-ext.hq.couchbase.com/builds/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-56.zip
2. Download couchbase-lite-java-listener-0.0.0-505.jar
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-java-listener/0.0.0-505/couchbase-lite-java-listener-0.0.0-505.jar
3. Download couchbase-lite-java-javascript-0.0.0-505.jar
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-java-javascript/0.0.0-505/couchbase-lite-java-javascript-0.0.0-505.jar
4. Move to your PhoneGap app folder
5. Update Plugin
phonegap plugin rm com.couchbase.lite.phonegap
phonegap plugin add ~/Downloads/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-56 <-- where you extract
phonegap platform rm android
mv ./couchbase-lite-java-javascript-0.0.0-505.jar ./plugins/com.couchbase.lite.phonegap/lib/android/
mv ./couchbase-lite-java-listener-0.0.0-505.jar ./plugins/com.couchbase.lite.phonegap/lib/android/
6. Add following two lines in plugin.xml
    <source-file src="lib/android/couchbase-lite-java-javascript-0.0.0-505.jar" target-dir="libs"/>
    <source-file src="lib/android/couchbase-lite-java-listener-0.0.0-505.jar" target-dir="libs"/>
7. Update plugin continue
phonegap platform add android
8. Run Android PhoneGap app
phonegap run android --verbose
```

Note: couchbase-lite-java-javascript-0.0.0-505.jar and couchbase-lite-java-listener-0.0.0-505.jar should be in the PhoneGapPlugin, but we have build issue now. 

Hope this helps you

Thanks!
Hideki

**Comment by zebra1024** [comment] 2015-04-01 19:10
Thanks for the build.
We get the following error with that build "Router unable to route request to do_POST_replicate"
Maybe this is related to https://github.com/couchbase/couchbase-lite-java-core/issues/537?

Can I get a build with your fix for that issue? Do you know when the next official build is scheduled?

Thanks

**Comment by hideki** [comment] 2015-04-01 19:17
Hi @zebra1024,

Currently we are building master branch version of PhoneGapPlugin. PhoneGapPlugin build takes additional steps. It should be ready by end of today. Thank you very much for your patience.

>> Do you know when the next official build is scheduled?

@zgramana Could you please answer for this release schedule question?

Thanks,
Hideki

**Comment by hideki** [comment] 2015-04-01 19:31
Hi @zebra1024,

Please download the latest PhoneGapPlugin from following link?
http://cbfs-ext.hq.couchbase.com/builds/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-61.zip

Command to update plugin
```
phonegap plugin rm com.couchbase.lite.phonegap
phonegap plugin add ~/Downloads/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-61
phonegap platform rm android
phonegap platform add android
phonegap run android
phonegap run android --verbose
```

Hope this build helps you!

Thanks,
Hideki

**Comment by zebra1024** [comment] 2015-04-03 12:48
Thanks Hideki,

We have the same error with the new build - Router unable to route request to do_POST_replicate when we try to start replication.

Any news on the next official build?

I our current app it is taking 8 minutes to create a view from about 9K objects. This view is creates in seconds on iOS.

Thanks again for your timely responses.

**Comment by hideki** [comment] 2015-04-03 17:25
Hi @zebra1024,

1) Could you please check if you could successfully update PhoneGapPlugin. Under plugins folder, do you have following jar files? Please check version number of files. Following is what I expect.
```
$:~/phonegap/todo-lite$ find . | grep jar
./plugins/com.couchbase.lite.phonegap/lib/android/cbl_collator_so-0.0.0-509.jar
./plugins/com.couchbase.lite.phonegap/lib/android/commons-io-2.0.1.jar
./plugins/com.couchbase.lite.phonegap/lib/android/couchbase-lite-android-0.0.0-509.jar
./plugins/com.couchbase.lite.phonegap/lib/android/couchbase-lite-java-core-0.0.0-509.jar
./plugins/com.couchbase.lite.phonegap/lib/android/couchbase-lite-java-javascript-0.0.0-509.jar
./plugins/com.couchbase.lite.phonegap/lib/android/couchbase-lite-java-listener-0.0.0-509.jar
./plugins/com.couchbase.lite.phonegap/lib/android/jackson-annotations-2.5.0.jar
./plugins/com.couchbase.lite.phonegap/lib/android/jackson-core-2.5.0.jar
./plugins/com.couchbase.lite.phonegap/lib/android/jackson-databind-2.5.0.jar
./plugins/com.couchbase.lite.phonegap/lib/android/rhino-1.7R3.jar
./plugins/com.couchbase.lite.phonegap/lib/android/servlet-2-3.jar
./plugins/com.couchbase.lite.phonegap/lib/android/stateless4j-2.5.0.jar
./plugins/com.couchbase.lite.phonegap/lib/android/webserver-2-3.jar
$:~/phonegap/todo-lite$ 
```

2) Needs log message to understand the problem
> We have the same error with the new build - Router unable to route request to do_POST_replicate when we try to start replication.

Could you please retrieve by using android's `adb` command?
`adb logcat`   <-- simple command

details:
http://developer.android.com/tools/help/logcat.html

3) Official build 
> Any news on the next official build?

This is project management decision making. 
@zgramana, could you please answer for this question?

4) View.updateIndex() performance
> I our current app it is taking 8 minutes to create a view from about 9K objects. This view is creates in seconds on iOS.

In original comment of this ticket, you described one view takes 3min to update, other view takes 20 min.
> One view takes a few seconds on iOS and 3 minutes on Android. Other views take upwards of 20 minutes.

Does updateIndex() performance improve from 20min to 8min? or does it become slower from 3min to 8min?

Thanks,
Hideki

**Comment by zgramana** [comment] 2015-04-03 21:52
@zebra1024 we hope to have a preview build of our next release, 1.1, announced on 4/10.

**Comment by zebra1024** [comment] 2015-04-04 17:10
Sorry about the timing misunderstanding - We isolated creation of the views and we have 15 views and it take about 8 minutes for each view for a total of about 2 hours with about 9K objects. I am working on the logcat info from the builds. We are using the Ionic framework as well if that helps.

I appreciate your help with this.

**Comment by zebra1024** [comment] 2015-04-05 23:35
I checked the jar files and the versions matched what you listed. I put the logcat log file at 
https://onedrive.live.com/redir?resid=51be9f93e9410e39!22889&authkey=!AOYxNgKMadaJCwg&ithint=file%2cods

**Comment by hideki** [comment] 2015-04-08 00:50
Hi @zebra1024, 
Thank you very much for log message. Currently we are solving the issue.  Please give us few days to fix replication issue.
Thanks!

**Comment by hideki** [comment] 2015-04-09 00:16
Hi @zebra1024,

Thank you very much for your patience. Please download PhoneGapPlugin which is built from master branch. http://cbfs-ext.hq.couchbase.com/builds/Couchbase-Lite-PhoneGap-Plugin_1.0.4-47-63.zip

If it possible, please update View.updateIndex() performance result?

Thanks,
Hideki

**Comment by zebra1024** [comment] 2015-04-09 20:21
Thanks,

That worked and reduced the generate views from about 2 hours to around 4 minutes. This is obviously much better and I definitely appreciate the increase. However, these views build in about 20 seconds on iOS so there is still room for improvement.

**Comment by hideki** [comment] 2015-04-09 21:11
@zebra1024 ,

Some idea to improve View.updateIndex()

1. Does your JSON document contains non-ASCII range characters? If yes, we could improve performance by working for custom collator.
2. What kind of Android device are you using for testing? If your device is 1GB memory device, memory usage could make updateIndex() slower.
3. Do you observe memory related log message? If so, we could improve by peak memory usage.
4. I knows number of documents are a lot. How about each document size? what is average document (JSON) size? This is also memory related.
5. As talked before, we use Rhino 1.7R3 for run JavaScript map/reduce codes. Can you try 1.7R5 (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Download_Rhino). you can overwrite Rhino jar file in PhoneGapPlugin.
6. Or we might be able to optimize to call JavaScript code in couchbase-lite-java-javascript.

Thanks,
Hideki

**Comment by hideki** [comment] 2015-04-10 19:42
Hi @zebra1024,

We'd like to identify if JavaScript engine makes map/reduce codes slow. Do you have time to try write a native (Java/Android) sample app to check the performance of`View.updateIndex()`?
If you don't have time, can we access your data through sync gateway to reproduce here?
Please let us know if it is possible.

Thanks,
Hideki

**Comment by hideki** [comment] 2015-04-15 20:39
Hi @zebra1024,
Do you have any update about this issue?

**Comment by zebra1024** [comment] 2015-04-20 13:39
We tried Rhino 1.7R5 and this triggered some runtime errors that cause the app to crash.
Our JSON documents should not contain non-ASCII characters. I tested on a GS5 which has 2GB or RAM and on the emulator which has 768 MB of RAM. I see garbage collection messages.

The new build behaves differently during our initial sync so we are working to resolve these issues.

I will work on providing access to the data in the sync gateway.

**Comment by hideki** [comment] 2015-04-20 16:57
Hi @zebra1024 

Thank you for your comment.

> We tried Rhino 1.7R5 and this triggered some runtime errors that cause the app to crash.

Thank you for trying 1.7R5. 

> Our JSON documents should not contain non-ASCII characters. I tested on a GS5 which has 2GB or RAM and on the emulator which has 768 MB of RAM. I see garbage collection messages.

With my experience, CBL Android works fine with 2GB device most of scenario. But, with less than 1GB device, it depends document size and number of documents.

> The new build behaves differently during our initial sync so we are working to resolve these issues.

Could you please describe how they are different? They should behave same.

> I will work on providing access to the data in the sync gateway.

Accessing  data could help us figure out the root cause. Thanks!

**Comment by hideki** [comment] 2015-05-19 21:46
- Duplicated with #630
- This could be solved by [PR](https://github.com/couchbase/couchbase-lite-java-javascript/pull/10)

**Comment by hideki** [comment] 2015-05-30 07:32
[PR](https://github.com/couchbase/couchbase-lite-java-javascript/pull/10) was merged. JavaScript map/reduce could improve its performance around 6times.

**Closed** 2015-05-30 07:32 UTC
Labels: enhancement, P2: medium, performance, S3: major, size-large
