### ISSUE TITLE
LiveQuery onChangeListener not working in 0.0.0-502

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-java-core#516] opened 2015-03-24 15:17 UTC
It seems like livequeries and change listeners are not invoking the events on new objects which came from cloud.
After more inspection it seems change listener works almost well (invoking events but  DocumentChange.getAddedRevision().getProperties() returns null)  but change listener on livequery is not firing events at all!

**Comment by hideki** [comment] 2015-03-24 17:16
Note to self: 
- First reproduce this issue.

**Comment by hideki** [comment] 2015-03-25 20:25
Hi @biokys 

Some notes for Event handling. 
(I didn't investigate LiveQuery issue yet, I will do it later.)

Replication.ChangeListener:
- This is not an event for retrieving the changed document.

Database.ChangeListener:
- This is a right event for retrieving the changed document.
- DocumentChange.getAddedRevision() is public method, but we don't have intention that user access this method. We added @InterfaceAudience.Private annotation for these methods, but it does not solve the issue. see. https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/DocumentChange.java#L55-L61 We should address this problem in the future.

Solution to access Document property:
- Please use Database.getDocument(document id): `Database.getDocument(ChangeEvent.getDocumentId()).getProperties()`

Example:
```
        database.addChangeListener(new Database.ChangeListener() {
            @Override
            public void changed(Database.ChangeEvent event) {
                Log.e(TAG, "Pull DB Event: " + event);
                List<DocumentChange> changes = event.getChanges();
                for(DocumentChange change:changes){
                    Log.e(TAG, change.toString());
                    //Log.e(TAG, change.getAddedRevision().getProperties().toString()); <-- NullPointer Exception
                    Log.e(TAG, pullDB.getDocument(change.getDocumentId()).getProperties().toString());
                }
            }
        });
```

**Comment by hideki** [comment] 2015-03-25 21:54
Hi @biokys,

I could not reproduce the issue about LiveQuery. LiveQuery.ChangeEvent is passed whenever pull replicator replicated documents from sync gateway. My test code is [here](https://github.com/hideki/couchbase-lite/tree/master/test/Issue471).

Whenever pulled replicator pulls a document from sync gateway, I observed Database.ChangeEvent and then LiveQuery.ChangeEvent. Following is log message from test app.
```
03-25 17:44:01.333    3217-3233/self.hideki.issue471 E/Issue 471﹕ Pull DB Event: com.couchbase.lite.Database$ChangeEvent@528ee1dc
03-25 17:44:01.333    3217-3233/self.hideki.issue471 E/Issue 471﹕ docId: 9fa63540-5b08-4850-a214-6c2ce2274a20 rev: 1-37c0941d3982edbac3d22e017ce1f2b5 isConflict: false sourceUrl: http://10.17.2.82:4984/db
03-25 17:44:01.333    3217-3233/self.hideki.issue471 E/Issue 471﹕ {_rev=1-37c0941d3982edbac3d22e017ce1f2b5, created_at=1.427319839258E12, _id=9fa63540-5b08-4850-a214-6c2ce2274a20, doc_counter=1}

03-25 17:44:01.349    3217-3233/self.hideki.issue471 E/Issue 471﹕ LiveQuery.ChangeEvent: {id=dff51db6-88f0-4156-a96d-835d818f7a15, value=1, key=1.427319211807E12}
```

As I could not reproduce the issue, I will close this ticket. If you still encounter the issue, please reopen the ticket with additional information? 

Thanks!

**Closed by hideki** 2015-03-25 21:54 UTC
Labels: bug, in progress, reproduce/investigate, testneeded
