### ISSUE TITLE
SIGSEGV / SIGSTKFLT with API 14 Arm 1.3.0-35 SQLite

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1365] opened 2016-07-21 00:26 UTC
I found this while testing with an Nexus 4 ARM API 14 emulator:

I was running `cbl-large-revisions.js` test with `1.3.0-35`, Shortly after this, there is a `signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)` and the app crashes. 

More verbose adb output - https://gist.github.com/sethrosetter/8eb437f9b5a03e5627a151937eb586e2#file-gistfile1-txt-L46-L85

```
E/AndroidRuntime( 3069): FATAL EXCEPTION: ChangeTracker-http://10.0.2.2:9888/db
E/AndroidRuntime( 3069): java.lang.IllegalArgumentException: Unexpected char 0x01 at 14 in header name: Accept-Encoding
E/AndroidRuntime( 3069): 	at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:312)
E/AndroidRuntime( 3069): 	at okhttp3.Headers$Builder.add(Headers.java:270)
E/AndroidRuntime( 3069): 	at okhttp3.Request$Builder.addHeader(Request.java:175)
E/AndroidRuntime( 3069): 	at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:306)
E/AndroidRuntime( 3069): 	at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:246)
E/AndroidRuntime( 3069): 	at java.lang.Thread.run(Thread.java:856)
W/ActivityManager(   96):   Force finishing activity com.couchbase.liteservandroid/.MainActivity
W/WindowManager(   96): Failure taking screenshot for (240x370) to layer 21010
W/RemoteRequest( 3069): com.couchbase.lite.replicator.RemoteRequest {POST, http://10.0.2.2:9888/db/_revs_diff}: executeRequest() Exception: java.lang.ArrayIndexOutOfBoundsException: size=7 offset=151 byteCount=1.  url: http://10.0.2.2:9888/db/_revs_diff
W/RemoteRequest( 3069): java.lang.ArrayIndexOutOfBoundsException: size=7 offset=151 byteCount=1
W/RemoteRequest( 3069): 	at okio.Util.checkOffsetAndCount(Util.java:30)
W/RemoteRequest( 3069): 	at okio.Buffer.getByte(Buffer.java:295)
W/RemoteRequest( 3069): 	at okio.Buffer.readUtf8Line(Buffer.java:653)
W/RemoteRequest( 3069): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
W/RemoteRequest( 3069): 	at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:438)
W/RemoteRequest( 3069): 	at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:422)
W/RemoteRequest( 3069): 	at okhttp3.internal.Util.skipAll(Util.java:178)
W/RemoteRequest( 3069): 	at okhttp3.internal.Util.discard(Util.java:160)
W/RemoteRequest( 3069): 	at okhttp3.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:459)
W/RemoteRequest( 3069): 	at okio.RealBufferedSource.close(RealBufferedSource.java:411)
W/RemoteRequest( 3069): 	at okio.RealBufferedSource$1.close(RealBufferedSource.java:399)
W/RemoteRequest( 3069): 	at java.io.FilterInputStream.close(FilterInputStream.java:64)
W/RemoteRequest( 3069): 	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:256)
W/RemoteRequest( 3069): 	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:148)
W/RemoteRequest( 3069): 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:242)
W/RemoteRequest( 3069): 	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:386)
W/RemoteRequest( 3069): 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3569)
W/RemoteRequest( 3069): 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2646)
W/RemoteRequest( 3069): 	at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:275)
W/RemoteRequest( 3069): 	at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
W/RemoteRequest( 3069): 	at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
W/RemoteRequest( 3069): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
W/RemoteRequest( 3069): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/RemoteRequest( 3069): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/RemoteRequest( 3069): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
W/RemoteRequest( 3069): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
W/RemoteRequest( 3069): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/RemoteRequest( 3069): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/RemoteRequest( 3069): 	at java.lang.Thread.run(Thread.java:856)
V/Database( 3069):     pruning large-revisions_2, scanning 41 revs in tree...
V/Batcher ( 3069): com.couchbase.lite.support.Batcher$2@4178e940: call processNow ..
```

**Comment by sethrosetter** [comment] 2016-07-21 01:03
1.2.1 does not exhibit this behavior. It seems to be a regression.

**Comment by sethrosetter** [comment] 2016-07-21 02:03
Running again crashed in a different way - https://gist.github.com/sethrosetter/51c9f8f383467c84cdb76ee11875685a

**Comment by hideki** [comment] 2016-07-21 02:05
Another log:
https://gist.github.com/hideki/f99a46d8a9d7842cfaf078d80f216e38

**Comment by hideki** [comment] 2016-07-21 18:52
NOTE:

> SIGSTKFLT happens when the device runs out of memory, esp. when using malloc() calls in the underlying linux OS layer. When the OS cannot return a fail in malloc, it generates a fatal signal of this kind.

**Comment by hideki** [comment] 2016-07-21 20:41
#### Changes since v1.2.1
- [ ] System SQLite to Custom SQLite
- [ ] Multiple SQLite connection if API > 19 - crash occurs API 14. <-- This crash occurs with API 14.
- [ ] Auto Prune
- [ ] Replaced HttpClient with OkHttp

**Comment by hideki** [comment] 2016-07-22 02:01
`cbl-large-revisions.js` functional test fails with v1.2.1 on Android ARM emulator with API 14. So this issue is not regression.

**Comment by hideki** [comment] 2016-07-22 03:45
Memory usage of LiteServ on Nexus4 ARM API14 emulator - 14MB out of 16MB. From this data without running functional test, LiteServ consumes 14MB.
![nexus4_arm_api14](https://cloud.githubusercontent.com/assets/15889/17045847/2cf887da-4f82-11e6-857a-8235428f6348.png)

Memory usage of LiteServ on Nexus4 x86 API19 emulator - 3.41MB is consumed by LiteServ without running functional test.
![nexus4 arm api21](https://cloud.githubusercontent.com/assets/15889/17045950/2bfc3db2-4f83-11e6-8070-20d06f46bec1.png)

From above memory usage, it seems ARM API 14 emulator is not good environment for functional test.

**Comment by hideki** [comment] 2016-07-22 07:56
Following is memory usage during functional test with using Nexus 4 ARM API 19 emulator. Maximum memory usage is around 5MB.

<img width="1513" alt="screen shot 2016-07-22 at 12 54 49 am" src="https://cloud.githubusercontent.com/assets/15889/17050297/f527213e-4fa6-11e6-9405-7c304ac4b31e.png">

**Comment by hideki** [comment] 2016-07-22 08:12
[cbl-large-revisions.js](https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-large-revisions.js)

#### Test Case
1. Create database on Client and Sync Gateway
1. Start continuous push replicator
1. Create 10 docs
1. Update docs on Sync Gateway (30 updates per docs)
1. Start continuous pull replicator
1. Delete docs in DB
1. Create 10 docs on client
1. Update 183 times per doc on client (6 * 30 + 3)
1. Delete docs in DB

**Comment by hideki** [comment] 2016-07-22 08:44
Note to self:
crash is also reproducible with Nexus 4 ARM emulator with API 14, 15 and 16.

**Comment by hideki** [comment] 2016-07-22 19:25
Test results with v1.2.1 to verity if this is regression

- Run test twice with LiteServ compiled with CBL v1.2. on Nexus 4 ARM emulator with API 14

Crash log form logcat
https://gist.github.com/hideki/10baa338f6842c605ca7302aa1f68f53

Functional Test Log:
https://gist.github.com/hideki/d91e42bffa1a475ebfe71e323c94846f

**Comment by sethrosetter** [comment] 2016-07-22 22:49
@hideki, I just reproduced this on the second run with 1.2.1

**Comment by sethrosetter** [comment] 2016-07-22 23:09
Crashed with ForestDB is roughly the same place

node output - https://gist.github.com/sethrosetter/dccf59351ab5fe372d53f27df9449f83
adb - https://gist.github.com/sethrosetter/640338f9b08f7aa0d11780aac66f21c1

**Comment by pasin** [comment] 2016-07-23 19:15
As the memory management on the API 14 - 18 ARM emulators doesn't work as expected, it's hard to confirm if this is the real issue or not. Also we currently do not have devices in those API range to test. I will close the issue as cannot verified. Once we have the real devices to test, we could revisit the issue.

**Closed by pasin** 2016-07-23 19:15 UTC
Labels: functional-test-failure, review, test
