### ISSUE TITLE
ToDoLite crashes during clear Cookie

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#964] opened 2016-01-29 06:49 UTC
It seems it requires to catch NOT_FOUND exception, and ignore it for this scenario.
See stack trace:
https://gist.github.com/sethrosetter/6fcb15e79e237a53e056

**Comment by sethrosetter** [comment] 2016-01-29 06:53
Steps to reproduce:
1. Sign in with User A
2. Add a few docs, make sure pointing at a running sync_gateway. 
3. Take db offline
```
curl -X POST http://localhost:4985/todos/_offline
```
4. Add a few docs
5. Bring db online
```
curl -X POST http://localhost:4985/todos/_online
```
6. This will log user A out and take you to the Facebook log out screen
7. Click log out. 
8. You will now be at the Facebook login in screen.
9. Log in with User B.
10. Log seems successful. but then the app will crash with the above stacktrace

**Comment by zgramana** [comment] 2016-01-29 22:25
I think this is a duplicate of #954.

**Closed** 2016-01-30 21:20 UTC
Labels: bug, release-prep, reproduce/investigate

**Comment by sethrosetter** [comment] 2016-02-01 20:16
@hideki I followed the repro steps above with CBLite 1.2.0-30 89039a10b0ccfc5e84ecf6b04bb96a24831b443f and the app not longer crashes when trying to log in with a new user.

**Comment by hideki** [comment] 2016-02-01 20:35
@sethrosetter Thank you very much for confirmation.
