### ISSUE TITLE
Nonsensical CouchbaseLiteException (Conflict) exception thrown on UnsavedRevision.save()

### ISSUE THREAD

**Issue by keith-redbite** [couchbase/couchbase-lite-java-core#479] opened 2015-03-11 13:58 UTC
Hi,

The bug is NOT always reproducible. I have an android's ApplicationTestCase that tries to replicate it by going through the following logic numerous times. (I have also seen this happening on JVM).

        Document document = database.createDocument();

        document.putProperties(Collections.<String,Object>singletonMap("test", "1"));
        document = document.getCurrentRevision().getDocument();

        SavedRevision savedRevision = document.getCurrentRevision();
        savedRevision.createRevision(Collections.<String,Object>singletonMap("test","2"));

        document = document.getCurrentRevision().getDocument();

        UnsavedRevision unsavedRevision = document.createRevision();
        unsavedRevision.setProperties(Collections.<String,Object>singletonMap("test","3"));
        unsavedRevision.save(); //Nonsensical conflict thrown here

        document = document.getCurrentRevision().getDocument();

        unsavedRevision = document.createRevision();
        unsavedRevision.setProperties(Collections.<String,Object>singletonMap("test","4"));
        unsavedRevision.save(); //Or here

## Exception

>com.couchbase.lite.CouchbaseLiteException: Conflicts not allowed and there is already an existing doc with id: 6bb93604-67d8-4f94-b0b3-6ca0803fd9c6
>at com.couchbase.lite.Database.putRevision(Database.java:3530)
>at com.couchbase.lite.Database.putRevision(Database.java:3465)
>at com.couchbase.lite.Document.putProperties(Document.java:415)
>at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:102)
>at com.redbite.RedStore.tests.CouchbaseLiteTest.tryMakeNonsensicalConflicts(CouchbaseLiteTest.java:87)
>at com.redbite.RedStore.tests.CouchbaseLiteTest.testNonsensicalConflicts(CouchbaseLiteTest.java:64)
>at java.lang.reflect.Method.invokeNative(Native Method)
>at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
>at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
>at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
>at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1792)

As the exception is not always thrown, I assumed that this is a bug instead of a misuse of the API. Please advise.

K

**Comment by keith-redbite** [comment] 2015-03-11 14:04
The android ApplicationTestCase I mentioned: 

https://www.dropbox.com/s/ei8u48trmhidj9m/CouchbaseLiteTest.java?dl=0

**Comment by keith-redbite** [comment] 2015-03-11 14:31
The test case was run against the following versions (issue occurs in all three) :

'com.couchbase.lite:couchbase-lite-android:1.0.4'
'com.couchbase.lite:couchbase-lite-android:1.0.3.1'
'com.couchbase.lite:couchbase-lite-android:1.0.3'

**Comment by keith-redbite** [comment] 2015-03-11 14:56
When ran against bleeding edge, a different exception was thrown: 

>java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
>at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
>at android.database.sqlite.SQLiteSession.setTransactionSuccessful(SQLiteSession.java:371)
>at android.database.sqlite.SQLiteDatabase.setTransactionSuccessful(SQLiteDatabase.java:540)
>at com.couchbase.lite.android.AndroidSQLiteStorageEngine.setTransactionSuccessful(AndroidSQLiteStorageEngine.java:88)
>at com.couchbase.lite.Database.endTransaction(Database.java:1266)
>at com.couchbase.lite.Database.putRevision(Database.java:3753)
>at com.couchbase.lite.Database.putRevision(Database.java:3526)
>at com.couchbase.lite.Document.putProperties(Document.java:417)
>at com.couchbase.lite.Document.putProperties(Document.java:252)
>at com.redbite.RedStore.tests.CouchbaseLiteTest.tryMakeNonsensicalConflicts(CouchbaseLiteTest.java:71)
>at com.redbite.RedStore.tests.CouchbaseLiteTest.testNonsensicalConflicts(CouchbaseLiteTest.java:64)
>at java.lang.reflect.Method.invokeNative(Native Method)
>at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
>at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
>at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
>at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1792)

**Comment by Takhion** [comment] 2015-03-11 16:09
Are you saving the documents from different threads?

**Comment by keith-redbite** [comment] 2015-03-11 16:14
Hi, 

No. The test case I attached only repeatedly run the logic in a single thread.

There is however, a live query that runs in the background, which does QueryRow.getDocument() and nothing more.

K

**Comment by keith-redbite** [comment] 2015-03-13 09:52
Hi,

Have anyone had a chance to look at this yet?

Thanks

**Comment by hideki** [comment] 2015-03-13 16:34
Hi @keith-redbite,
This ticket is still in the queue. We have around 45 open tickets for CBL Java Core. We will try to look into the issue as soon as possible.

**Comment by hideki** [comment] 2015-04-07 17:47
Note to self: Try to sync against CouchDB

**Comment by hideki** [comment] 2015-04-08 23:17
check https://github.com/couchbase/couchbase-lite-net/issues/388

**Comment by hideki** [comment] 2015-04-09 22:07
Hi @keith-redbite,

I have tried to reproduce the issue, so far I could not. I tested your test code against master branch and release/1.0.4 branch with real device and android emulator

Unit test code I used:
https://github.com/couchbase/couchbase-lite-android/commit/5071b3ad18e7dbe5219fbf1c3673a8c7e43e68a2

Do you have any additional information to reproduce this?

Thanks,

**Comment by keith-redbite** [comment] 2015-04-10 09:00
@hideki, did you add in the live query and change listener? 
Note that the listener does NOT modify the doc in any way.

Also, it always take (for me) around 500-1000 iterations for the exception to be thrown.
It's hard to pin down the actual cause as its doesn't always happen.


<code>
        View testNonsensicalConflict = database.getView("testNonsensicalConflict");

        testNonsensicalConflict.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                emitter.emit(null,null);
            }
        }, "");
        Query query = testNonsensicalConflict.createQuery();
        LiveQuery liveQuery = query.toLiveQuery();

        liveQuery.addChangeListener(new LiveQuery.ChangeListener() {
            @Override
            public void changed(LiveQuery.ChangeEvent event) {
                QueryEnumerator rows = event.getRows();
 
                while(rows.hasNext()){
                    QueryRow next = rows.next();
                    next.getDocument();
                }
            }
        });
 
        liveQuery.run();
</code>

**Comment by hideki** [comment] 2015-04-10 17:30
Hi @keith-redbite,

II don't understand the relationship between `updating document` and `LiveQuery`. Do you think `LiveQuery` might cause the conflict?

Don't you mind if you post full test codes here?

Thank you very much for your help!
Hideki

**Comment by hideki** [comment] 2015-04-10 23:19
Hi @keith-redbite,

I added LiveQuery codes into test case. See https://github.com/couchbase/couchbase-lite-android/commit/a70c1ab845c4c0126bbc8361437b71c51cf58afd
However, still unable to reproduce the problem.
Could you please check if test code I implemented is correct to reproduce the problem.

Thanks!
Hideki

**Comment by keith-redbite** [comment] 2015-04-14 16:08
Hi @hideki 

The TestCase you've written seems sufficient to reproduce the problem. Also, I've already included the test case in an earlier post:

https://www.dropbox.com/s/ei8u48trmhidj9m/CouchbaseLiteTest.java?dl=0

I suspect that the LiveQuery somehow causes the exception to be thrown, as the exception is not observed if the LiveQuery is inactive. This issue occurs more frequently in our production code which have quite a number of LiveQuery running (~10) i.e. likelihood of exception being thrown scales with number of active LiveQuery.

I've also re-run the test against following versions:

1.0.4 (from maven: repo) :  FAILED
1.0.4 (from release/1.0.4: 72b230) : FAILED
bleeding edge (from master: c0e0d3fe) : PASSED

It seems that some changes in bleeding edge resolved the issue, though I can't speculate what it might be.

In any case, when will the next schedule released be? Will there be a hot-fix release for 1.0.4?

Cheers!
Keith

**Comment by hideki** [comment] 2015-04-14 19:25
Hi @keith-redbite,

Thank you very much for your reply. I will retest with 1.0.4 again.

Release schedule: Preview release for next version could be end of this week. And official next release could be around end of this month. But this is plan. 

Thanks!

**Comment by hideki** [comment] 2015-04-15 19:11
Hi @keith-redbite ,
I tested with CBL Android v1.0.4. And I could reproduce the problem.
However, as you wrote in previous comments, I still could not reproduce the issue with master branch version of CBL Android. I assume that fix for other issue also fixed this issue too. 
I will close this ticket. If you still encounter this problem with master branch or next version of release (v1.1.0), please let us know.
Thanks!

**Closed by hideki** 2015-04-15 19:11 UTC
Labels: bug, P2: medium, S3: major, size-large
