### ISSUE TITLE
ForestDB exception in query iterator

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#971] opened 2016-02-01 20:33 UTC
In following the steps to verify https://github.com/couchbase/couchbase-lite-java-core/issues/964#issuecomment-176606050, I noticed the below exception when logging in at step 4 (now successfully logs in) 

```
02-01 12:12:17.636 15216-15216/? D/ToDoLite: Turn on progress spinny
02-01 12:12:17.646 15216-15216/? D/ToDoLite: Sync progress changed.  Completed: 0 Total: 0 Status: REPLICATION_ACTIVE
02-01 12:12:17.646 15216-15248/? E/View: Error in regularQuery()
                                         ForestException{domain=2, code=-12}
                                             at com.couchbase.cbforest.QueryIterator.next(Native Method)
                                             at com.couchbase.cbforest.QueryIterator.next(QueryIterator.java:9)
                                             at com.couchbase.lite.store.ForestDBViewStore.regularQuery(ForestDBViewStore.java:363)
                                             at com.couchbase.lite.View.query(View.java:358)
                                             at com.couchbase.lite.Database.queryViewNamed(Database.java:2108)
                                             at com.couchbase.lite.Query$2.run(Query.java:483)
                                             at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                             at java.lang.Thread.run(Thread.java:841)
02-01 12:12:17.646 15216-15216/? D/ToDoLite: Turn on progress spinny
```

Full gist - https://gist.github.com/sethrosetter/93dd0a88503cf28aefa0#file-gistfile1-txt-L4-L17

**Comment by snej** [comment] 2016-02-01 20:40
Error -12 is `FDB_RESULT_ITERATOR_FAIL` which is what ForestDB returns at the end of an iteration, but it shouldn't be passed on to Java as an exception.

**Comment by hideki** [comment] 2016-02-01 20:41
@snej, Thank you for your input.

**Comment by snej** [comment] 2016-02-01 20:50
This looks like a bug in the CBForest C API, and I'm wondering if it's a regression from Friday's fix. Does this show up in unit tests?

**Comment by snej** [comment] 2016-02-01 21:12
So, I have a PR with a speculative fix for this (see above) ... how can we test it out? @hideki or @sethrosetter, could you apply that change (2 lines), build ToDoLite, and try the steps to verify #964?

**Comment by hideki** [comment] 2016-02-01 21:42
Hi @snej,
By applying your [fix](https://github.com/couchbaselabs/cbforest/pull/60), this Exception is no longer  printed.
Thank you very much for your quick fix!

**Comment by zgramana** [comment] 2016-02-01 21:59
@hideki I'll keep this issue open until you can confirm that new CBForest binaries are built and packaged.

**Comment by sethrosetter** [comment] 2016-02-02 00:26
As of 1.2.0-32 (41bbb374674612eaaa513a709deb5862360dcc8b), I am not longer able to the above Exception when following the steps to reproduce.

**Comment by sethrosetter** [comment] 2016-02-02 00:28
@zgramana I have verified that I can no longer repro the exception after testing with the build above. I will leave it to you to close per your comment above.

**Comment by zgramana** [comment] 2016-02-02 17:53
:+1:

**Closed by zgramana** 2016-02-02 17:53 UTC
Labels: bug, release-prep
