### ISSUE TITLE
Starting an AsyncTask right after Document.putProperties(), does not call the doInBackround() method?

### ISSUE THREAD

**Issue by ashwinbhaskar** [couchbase/couchbase-lite-java-core#587] opened 2015-04-23 12:06 UTC
I am not sure if this is an issue or a miss in the documentation. But when ever I am triggering an AsyncTask right after document.puProperties(), the doInBacground() method of the AsyncTask is not triggered.

```document.putProperties(fields);
document_message.putProperties(fields_message);
myAsyncTask.execute();
```
The call to `doInBackground()` rarely takes place. But when I modify the code to the following 
```document.putProperties(fields);
document_message.putProperties(fields_message);
myAsyncTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
```
the call to 'doInBackground()' happens. 

Android supports the execution of onl 1 AsyncTask at a time. To execute multiple AsyncTask we need to use the `executeOnExecutor()` function. 
So, does a call to `document.putProperties()` trigger an AsyncTask internally. If so, I think it should be documented somewhere. If I am not wrong it is not documented right now.

**Comment by sergio91pt** [comment] 2015-04-23 12:54
Altough there is an interface called AsyncTask it does not use Android's AsyncTask, and couchbase-lite-android also does not use AsyncTask.

If one task is hanging your executor, try to find out what code is doing so. The serial executor runs its tasks on THREAD_POOL_EXECUTOR, so look at the stacktraces of AsyncTask thread's, using the device monitor.

**Comment by hideki** [comment] 2015-04-24 07:28
Hi @ashwinbhaskar,

CBL Android does not use `android.os.AsyncTask`. To support both Android and J2SE, CBL Android/Java uses [ScheduledExecutorService](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html).

Thanks,

**Comment by ashwinbhaskar** [comment] 2015-04-24 07:48
Hmm. Since, ScheduledExecutorService spawns new threads, is there any possiblity that they could be the reason for blocking AsyncTask.execute() ?
 Because my code uses only 1 AsyncTask at that time. And there is no other AsyncTask running.

**Comment by hideki** [comment] 2015-04-24 17:16
Hi @ashwinbhaskar
> Hmm. Since, ScheduledExecutorService spawns new threads, is there any possibility that they could be the reason for blocking AsyncTask.execute() ?
I am not sure. So we need to investigate.

Could you please provide us the codes that reproduce this issue? It will help us a lot.

Thanks!

**Comment by hideki** [comment] 2015-05-05 01:42
Hi @ashwinbhaskar,

I wrote simple unit test for `Document.putProperties()` method with using AsyncTask. So far, I am not able to reproduce the issue. Could you please review following codes?

```
    private class TestAsyncTask extends android.os.AsyncTask<CountDownLatch, Void, Void> {
        @Override
        protected Void doInBackground(CountDownLatch... latches) {
            int count = latches.length;
            for (int i = 0; i < count; i++) {
                latches[i].countDown();
            }
            return null;
        }
    }

    /**
     * Starting an AsyncTask right after Document.putProperties(), does not call the doInBackround() method?
     * https://github.com/couchbase/couchbase-lite-java-core/issues/587
     */
    public void testPutPropertiesWithAsyncTask() throws CouchbaseLiteException, InterruptedException {
        Document document = database.createDocument();
        Map<String, Object> properties = new HashMap<String, Object>();
        properties.put("foo", "foo");
        properties.put("bar", Boolean.FALSE);
        document.putProperties(properties);
        Assert.assertNotNull(document.getCurrentRevisionId());
        Assert.assertNotNull(document.getCurrentRevision());
        CountDownLatch latch = new CountDownLatch(1);
        new TestAsyncTask().execute(latch);
        assertTrue(latch.await(5, TimeUnit.SECONDS));
    }
```

Thanks!
Hideki

**Comment by hideki** [comment] 2015-05-08 18:56
Hi @ashwinbhaskar,
Do you have any additional information to reproduce the issue? With previous comment's test code, we can not reproduce the issue. For now, I will close this ticket. If you still encounter this problem, please reopen the ticket. 
Have a nice weekend!

**Closed by hideki** 2015-05-08 18:56 UTC
Labels: bug, in progress, needsmoreinfo, release-prep, reproduce/investigate, S3: major, size-large
