### ISSUE TITLE
ForestDB CBL crash.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-core#1276] opened 2016-06-20 09:08 UTC
Hi Folks,
Continuous Pull and Push sync is active, random CBL forest DB crash seen.

**CBL logs:**
```
[06/15 03:10:11.794] [1240] RemoteRequest: RemoteRequest{GET, https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true}: executeRequest() finally
[06/15 03:10:11.821] [971] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@1e35f518: RemoteRequestRetry inner request finished, url: https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true
[06/15 03:10:11.822] [971] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@1e35f518: RemoteRequestRetry was successful, calling callback url: https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true
[06/15 03:10:11.822] [971] Sync: PullerInternal{unknown, pull, 673e5}: pullRemoteRevision add rev: {s919879872020_ptx1465983604397_meta.doc #3-82f3249a40ffcab9fd0add2ca5f39a1d @22} to batcher: com.couchbase.lite.support.Batcher@235637df
[06/15 03:10:11.822] [971] Batcher: com.couchbase.lite.support.Batcher@235637df: queueObjects called with 1 objects (current inbox size = 0)
[06/15 03:10:11.823] [971] Batcher: com.couchbase.lite.support.Batcher@235637df: scheduleWithDelay 250 ms, scheduled ...
[06/15 03:10:11.823] [971] RemoteRequest: RemoteRequest{GET, https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true}: executeRequest() finally
[06/15 03:10:11.863] [651] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@369e0d56: RemoteRequestRetry inner request finished, url: https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true
[06/15 03:10:11.864] [651] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@369e0d56: RemoteRequestRetry was successful, calling callback url: https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true
[06/15 03:10:11.864] [651] Sync: PullerInternal{unknown, pull, 673e5}: pullRemoteRevision add rev: {s919879872020_ptx1465983604397_meta.doc #3-82f3249a40ffcab9fd0add2ca5f39a1d @22} to batcher: com.couchbase.lite.support.Batcher@5f6bb79
[06/15 03:10:11.865] [651] Batcher: com.couchbase.lite.support.Batcher@5f6bb79: queueObjects called with 1 objects (current inbox size = 0)
[06/15 03:10:11.865] [651] Batcher: com.couchbase.lite.support.Batcher@5f6bb79: scheduleWithDelay 250 ms, scheduled ...
[06/15 03:10:11.865] [651] RemoteRequest: RemoteRequest{GET, https://bsyncg.kodiakhsqc.com:443/ptxdata/s919879872020_ptx1465983604397_meta.doc?rev=3-82f3249a40ffcab9fd0add2ca5f39a1d&revs=true&attachments=true}: executeRequest() finally
[06/15 03:10:12.044] [1214] Batcher: com.couchbase.lite.support.Batcher$2@fe011d7: call processNow ...
[06/15 03:10:12.046] [1214] Batcher: com.couchbase.lite.support.Batcher@1e560f8d: processNow() called, inbox size: 1
[06/15 03:10:12.048] [1214] Batcher: com.couchbase.lite.support.Batcher@1e560f8d: invoking processor com.couchbase.lite.replicator.PullerInternal$2@372f2f2b with 1 items
[06/15 03:10:12.049] [1214] Sync: PullerInternal{unknown, pull, 673e5} inserting 1 revisions...
[06/15 03:10:12.057] [1214] Sync: com.couchbase.lite.replicator.PullerInternal$9@2b214ac4: inserting s919879872020_ptx1465983604397_meta.doc [3-82f3249a40ffcab9fd0add2ca5f39a1d, 2-b70fdea84e727094468a98a7f531f393, 1-8a87b30dbca09f81b51e40d7cbda5f1d]
[06/15 03:10:12.059] [1214] Database: INSERT {s919879872020_ptx1465983604397_meta.doc #3-82f3249a40ffcab9fd0add2ca5f39a1d @4}, history[3]
[06/15 03:10:12.065] [1214] CBLite: ---> Added: {s919879872020_ptx1465983604397_meta.doc #3-82f3249a40ffcab9fd0add2ca5f39a1d @0} as seq 0
[06/15 03:10:12.066] [1214] Sync: com.couchbase.lite.replicator.PullerInternal$9@2b214ac4: finished inserting 1 revisions
[06/15 03:10:12.067] [1214] Sync: PullerInternal{unknown, pull, 673e5}: Setting lastSequence to 196027::196258 from(196027::196256)
[06/15 03:10:12.070] [1214] Sync: com.couchbase.lite.replicator.PullerInternal$9@2b214ac4: inserted 1 revs in 16 milliseconds
[06/15 03:10:12.071] [1214] Sync: com.couchbase.lite.replicator.PullerInternal$9@2b214ac4 insertDownloads() updating completedChangesCount from 1 -> 2 
[06/15 03:10:12.073] [1214] Sync: PullerInternal{unknown, pull, 673e5}: Incrementing completedChangesCount count from 1 by adding 1 -> 2
[06/15 03:10:12.073] [683] Batcher: com.couchbase.lite.support.Batcher$2@198cbdad: call processNow ...
[06/15 03:10:12.075] [1214] CBLite: setPaused: false
[06/15 03:10:12.076] [683] Batcher: com.couchbase.lite.support.Batcher@235637df: processNow() called, inbox size: 1
[06/15 03:10:12.078] [683] Batcher: com.couchbase.lite.support.Batcher@235637df: invoking processor com.couchbase.lite.replicator.PullerInternal$2@3287f86e with 1 items
[06/15 03:10:12.087] [683] Sync: PullerInternal{unknown, pull, 673e5} inserting 1 revisions...
[06/15 03:10:12.090] [683] Sync: com.couchbase.lite.replicator.PullerInternal$9@2385a8e2: inserting s919879872020_ptx1465983604397_meta.doc [3-82f3249a40ffcab9fd0add2ca5f39a1d, 2-b70fdea84e727094468a98a7f531f393, 1-8a87b30dbca09f81b51e40d7cbda5f1d]
[06/15 03:10:12.092] [683] Database: INSERT {s919879872020_ptx1465983604397_meta.doc #3-82f3249a40ffcab9fd0add2ca5f39a1d @22}, history[3]
[06/15 03:10:12.115] [639] Batcher: com.couchbase.lite.support.Batcher$2@1a29f473: call processNow ...
[06/15 03:10:12.116] [683] Database: ForestDB Error: forceInsert()
com.couchbase.cbforest.ForestException: Forestdb Handle is being used by another thread
	at com.couchbase.cbforest.Document.init(Native Method)
	at com.couchbase.cbforest.Document.<init>(Document.java:97)
	at com.couchbase.cbforest.Database.getDocument(Database.java:46)
	at com.couchbase.lite.store.ForestDBStore$4.run(ForestDBStore.java:961)
	at com.couchbase.lite.store.ForestDBStore.inTransaction(ForestDBStore.java:1371)
	at com.couchbase.lite.store.ForestDBStore.forceInsert(ForestDBStore.java:955)
	at com.couchbase.lite.Database.forceInsert(Database.java:1809)
	at com.couchbase.lite.replicator.PullerInternal$9.run(PullerInternal.java:568)
	at com.couchbase.lite.store.ForestDBStore.runInTransaction(ForestDBStore.java:297)
	at com.couchbase.lite.replicator.PullerInternal.insertDownloads(PullerInternal.java:550)
	at com.couchbase.lite.replicator.PullerInternal$2.process(PullerInternal.java:115)
	at com.couchbase.lite.support.Batcher.processNow(Batcher.java:383)
	at com.couchbase.lite.support.Batcher.access$300(Batcher.java:16)
	at com.couchbase.lite.support.Batcher$2.run(Batcher.java:317)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

[06/15 03:10:12.119] [683] Sync: com.couchbase.lite.replicator.PullerInternal$9@2385a8e2: failed to write {s919879872020_ptx1465983604397_meta.doc #3-82f3249a40ffcab9fd0add2ca5f39a1d @22}: status=-1
[06/15 03:10:12.119] [683] Sync: PullerInternal{unknown, pull, 673e5}: Progress: set error = org.apache.http.client.HttpResponseException
[06/15 03:10:12.120] [683] Sync: com.couchbase.lite.replicator.PullerInternal$9@2385a8e2: finished inserting 1 revisions
[06/15 03:10:12.121] [683] Sync: com.couchbase.lite.replicator.PullerInternal$9@2385a8e2: inserted 1 revs in 32 milliseconds
[06/15 03:10:12.122] [683] Sync: com.couchbase.lite.replicator.PullerInternal$9@2385a8e2 insertDownloads() updating completedChangesCount from 21 -> 22 
[06/15 03:10:12.123] [683] Sync: PullerInternal{unknown, pull, 673e5}: Incrementing completedChangesCount count from 21 by adding 1 -> 22
[06/15 03:10:12.117] [639] Batcher: com.couchbase.lite.support.Batcher@5f6bb79: processNow() called, inbox size: 1
[06/15 03:10:12.134] [639] Batcher: com.couchbase.lite.support.Batcher@5f6bb79: invoking processor com.couchbase.lite.replicator.PullerInternal$2@16fe26b3 with 1 items
[06/15 03:10:12.134] [639] Sync: PullerInternal{unknown, pull, 673e5} inserting 1 revisions...
[06/15 03:10:12.135] [683] CBLite: setPaused: false
[06/15 03:10:12.250] [1237] Batcher: com.couchbase.lite.support.Batcher@39cdc2ea: waitForPendingFutures is called ...
[06/15 03:10:12.251] [1237] Batcher: com.couchbase.lite.support.Batcher@39cdc2ea: waitForPendingFutures done
[06/15 03:10:12.252] [1238] Batcher: com.couchbase.lite.support.Batcher@1563d000: waitForPendingFutures is called ...
[06/15 03:10:12.253] [1238] Batcher: com.couchbase.lite.support.Batcher@1563d000: waitForPendingFutures done
[06/15 03:10:12.254] [1239] Batcher: com.couchbase.lite.support.Batcher@d4b1c5: waitForPendingFutures is called ...
[06/15 03:10:12.255] [1239] Batcher: com.couchbase.lite.support.Batcher@d4b1c5: waitForPendingFutures done
[06/15 03:10:12.650] [1237] Batcher: com.couchbase.lite.support.Batcher@1e560f8d: waitForPendingFutures is called ...
[06/15 03:10:12.650] [1238] Batcher: com.couchbase.lite.support.Batcher@235637df: waitForPendingFutures is called ...
[06/15 03:10:12.650] [1239] Batcher: com.couchbase.lite.support.Batcher@5f6bb79: waitForPendingFutures is called ...
[06/15 03:10:12.769] [8] Listener: authHeader is null
[06/15 03:10:12.770] [8] Listener: Not enforcing basic auth -- allowedCredentials null or empty
[06/15 03:10:12.771] [8] Sync: PullerInternal{unknown, pull, 99681} [fireTrigger()] => STOP_GRACEFUL
[06/15 03:10:12.771] [1219] Sync: firing trigger: STOP_GRACEFUL
[06/15 03:10:12.772] [1219] Sync: PullerInternal{unknown, pull, 99681} [onExit()] IDLE => STOPPING
[06/15 03:10:12.772] [1219] Sync: State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: PullerInternal{unknown, pull, 99681}
[06/15 03:10:12.772] [1219] Sync: PullerInternal{unknown, pull, 99681} [onExit()] IDLE => STOPPING
[06/15 03:10:12.772] [1219] Sync: PullerInternal{unknown, pull, 99681} [onEntry()] IDLE => STOPPING
[06/15 03:10:12.773] [1219] Sync: PullerInternal{unknown, pull, 99681} STOPPING...
[06/15 03:10:12.773] [1219] ChangeTracker: ChangeTracker{https://---:---@bsyncg.kodiakhsqc.com:443/pttdata, OneShot, @35fb2d43}: Changed tracker asked to stop
[06/15 03:10:12.773] [1219] CBLite: setPaused: false
[06/15 03:10:12.774] [1219] ChangeTracker: ChangeTracker{https://---:---@bsyncg.kodiakhsqc.com:443/pttdata, OneShot, @35fb2d43}: Changed tracker aborting request: org.apache.http.client.methods.HttpPost@304a4f30
[06/15 03:10:12.775] [1222] ChangeTracker: ChangeTracker{https://---:---@bsyncg.company:443/pttdata, OneShot, @35fb2d43}: Change tracker run loop exiting
[06/15 03:10:12.775] [1222] ChangeTracker: ChangeTracker{https://---:---@bsyncg.company:443/pttdata, OneShot, @35fb2d43}: Change tracker in stopped()
[06/15 03:10:12.775] [1222] ChangeTracker: ChangeTracker{https://---:---@bsyncg.company:443/pttdata, OneShot, @35fb2d43}: Change tracker calling changeTrackerStopped, client: PullerInternal{unknown, pull, 99681}
[06/15 03:10:12.778] [1219] Batcher: com.couchbase.lite.support.Batcher@16c30ca2: flushing all objects (wait=false)
[06/15 03:10:12.779] [1219] Sync: State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: PullerInternal{unknown, pull, 99681}
[06/15 03:10:12.780] [1219] Sync: changeTrackerStopped.  lifecycle: ONESHOT
[06/15 03:10:12.780] [1219] ChangeTracker: ChangeTracker{https://---:---@bsyncg.company:443/pttdata, OneShot, @35fb2d43}: getLastError() null
[06/15 03:10:12.794] [1241] Sync: PullerInternal{unknown, pull, 99681} [fireTrigger()] => STOP_IMMEDIATE
[06/15 03:10:12.795] [1241] Sync: PullerInternal stop.run() finished
[06/15 03:10:12.796] [1219] Sync: firing trigger: STOP_IMMEDIATE
[06/15 03:10:12.796] [1219] Sync: PullerInternal{unknown, pull, 99681} [onEntry()] STOPPING => STOPPED
[06/15 03:10:12.799] [1219] Sync: PullerInternal{unknown, pull, 99681}: clearDbRef() called
[06/15 03:10:12.810] [1219] Sync: PullerInternal{unknown, pull, 99681}: clearDbRef() setting db to null
[06/15 03:10:12.810] [1219] Sync: State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: PullerInternal{unknown, pull, 99681}
[06/15 03:10:12.812] [1242] Sync: [waitForPendingFutures()] STARTED - thread id: 6480
[06/15 03:10:12.812] [1242] Sync: PullerInternal{unknown, pull, 99681} [fireTrigger()] => STOP_GRACEFUL
[06/15 03:10:12.813] [1219] Sync: firing trigger: STOP_GRACEFUL
[06/15 03:10:12.813] [1242] Sync: [waitForPendingFutures()] END - thread id: 6480




**ADB traces:**



06-15 15:10:12.874 I/DEBUG   (  282): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------

06-15 15:10:12.874 D/StatusBarManagerService(  955): manageDisableList userId=0 what=0x0 pkg=WindowManager.LayoutParams

06-15 15:10:12.884 I/ActivityManager(  955): Displayed com.android.documentsui/.DocumentsActivity: +199ms

06-15 15:10:12.884 W/ContextImpl(  955): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1687 com.android.server.InputMethodManagerService$6.run:2738 java.lang.Thread.run:818 <bottom of call stack> <bottom of call stack> 

06-15 15:10:12.894 D/Documents(32579): Before filtering 0, after 0

06-15 15:10:12.894 D/Documents(32579): Before filtering 1, after 0

06-15 15:10:12.904 D/Documents(32579): Before filtering 14, after 2

06-15 15:10:12.904 I/Timeline(32579): Timeline: Activity_idle id: android.os.BinderProxy@2b32d90 time:5238324

06-15 15:10:12.904 D/Documents(32579): Before filtering 46, after 0

06-15 15:10:12.904 D/Documents(32579): Found 4 of 4 recent queries done

06-15 15:10:12.944 D/PanelView( 1186): mClearAll.setVisibility - mIsFullyOpened : false isShade : true mHasNotification : true mIsUpwardFling : false mQsFullyExpanded : false isShadeLocked : false mClearAllVisible : true

06-15 15:10:12.944 D/PanelView( 1186): mClearAll.setVisibility - mIsFullyOpened : false isShade : true mHasNotification : true mIsUpwardFling : false mQsFullyExpanded : false isShadeLocked : false mClearAllVisible : true

06-15 15:10:12.964 D/PanelView( 1186): mClearAll.setVisibility - mIsFullyOpened : false isShade : true mHasNotification : true mIsUpwardFling : false mQsFullyExpanded : false isShadeLocked : false mClearAllVisible : true

06-15 15:10:12.964 I/DEBUG   (  282):     r0 00000000  r1 00004846  r2 00000006  r3 00000000

06-15 15:10:12.964 I/DEBUG   (  282):     r4 6faf3db8  r5 00000006  r6 0000006e  r7 0000010c

06-15 15:10:12.964 I/DEBUG   (  282):     r8 12fbb9a0  r9 9f915800  sl 00000001  fp 13ed9820

06-15 15:10:12.974 I/DEBUG   (  282):     ip 00004846  sp 6faf3680  lr b6eb2fc9  pc b6ed6acc  cpsr 600f0010

06-15 15:10:12.974 I/DEBUG   (  282): 

06-15 15:10:12.974 I/DEBUG   (  282): backtrace:

06-15 15:10:12.974 I/DEBUG   (  282):     #00 pc 00037acc  /system/lib/libc.so (tgkill+12)

06-15 15:10:12.974 I/DEBUG   (  282):     #01 pc 00013fc5  /system/lib/libc.so (pthread_kill+52)

06-15 15:10:12.974 I/DEBUG   (  282):     #02 pc 00014be3  /system/lib/libc.so (raise+10)

06-15 15:10:12.974 I/DEBUG   (  282):     #03 pc 00011529  /system/lib/libc.so (__libc_android_abort+36)

06-15 15:10:12.974 I/DEBUG   (  282):     #04 pc 0000fcb4  /system/lib/libc.so (abort+4)

06-15 15:10:12.974 I/DEBUG   (  282):     #05 pc 001c7419  /data/app/com.app.company-1/lib/arm/libCouchbaseLiteJavaForestDB.so (__gnu_cxx::__verbose_terminate_handler()+220)

06-15 15:10:12.974 I/DEBUG   (  282):     #06 pc 00197187  /data/app/com.app.company-1/lib/arm/libCouchbaseLiteJavaForestDB.so (__cxxabiv1::__terminate(void (*)())+2)

06-15 15:10:12.974 I/DEBUG   (  282):     #07 pc 001971b7  /data/app/com.app.company-1/lib/arm/libCouchbaseLiteJavaForestDB.so (std::terminate()+10)

06-15 15:10:12.974 I/DEBUG   (  282):     #08 pc 000f3fed  /data/app/com.app.company-1/lib/arm/libCouchbaseLiteJavaForestDB.so
```

Thanks
Nithin

**Comment by hideki** [comment] 2016-06-20 16:48
Hi @NitzDKoder,
Thank you for bug report. Could you please provide CBL version number?

**Comment by NitzDKoder** [comment] 2016-06-20 17:17
@hideki below forestdb cbl 1.2 was used..
 http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-700/

**Comment by NitzDKoder** [comment] 2016-06-20 17:18
Worngly closed..

**Comment by hideki** [comment] 2016-06-20 17:23
@NitzDKoder 
v1.2.0 has crush issue with ForestDB. Could you please try 1.2.1 or latest build from master branch 0.0.0-xxx?

**Comment by NitzDKoder** [comment] 2016-06-20 17:26
Sure..any obivious issues pointing to crash stack trace?

**Comment by hideki** [comment] 2016-06-20 17:36
most of ForestDB related crashes were caused by accessing ForestDB after closed ForestDB by other threads or accessing ForestDB from multiple threads concurrently. ForestDB is not thread safe, so we added thread safety in wrapper of forestdb. But it was not sufficient.

**Comment by NitzDKoder** [comment] 2016-06-20 17:40
Used patch build from https://github.com/couchbase/couchbase-lite-java-core/issues/1177..
Alright lets see 1.21 or master will address this? So any fixed planned for thread safe?

**Comment by hideki** [comment] 2016-06-20 17:45
We believe latest version is thread-safe. However, we might not cover all scenario. If you find any forestdb issue, please let us know.

**Comment by hideki** [comment] 2016-06-24 19:22
Hi @NitzDKoder,
Did you have chance to test  with build from latest master branch?

**Comment by hideki** [comment] 2016-06-29 07:14
I will close this ticket. If you are still encountering this issue, please reopen.

**Closed** 2016-06-29 07:14 UTC
Labels: bug, forestdb
