### ISSUE TITLE
List not syncing during test fest (Need to reproduce).

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-java-core#1557] opened 2017-01-17 00:33 UTC
Env
2 devices
- Android version - 1.4-18
- Sync gateway, di, 1.4-31
- Hideki (Nexus 5 - ForestDB + Encryption - emulator)
- Raghu (Nexus 6p - Android 7.1.1 - SQLCipher)

Scenario
- Hideki creates list, shares with raghu, raghu does not see it.
- Possible SQLCipher bug?
- Raghu deleted the / rebuilt app, now can see it

**Comment by hideki** [comment] 2017-01-17 00:41
@sethrosetter,

From today's observation, Android device successfully pushed the document on the sync gateway. But it seems that to pull the document from sync gateway failed. I assume this is not query issue because the re-starting app could not solve the issue.

I believe this issue is hard to reproduce. Can we retest this scenario more than a couple of times?

**Comment by hideki** [comment] 2017-01-31 23:13
We tried 3 times to reproduce this issue 01/31/2017. But we could not reproduce this. I will close this.

**Closed** 2017-01-31 23:13 UTC
Labels: P1: high, reproduce/investigate
