### ISSUE TITLE
Android,replication algorithm 1.0.3 stalls before replicating all documents

### ISSUE THREAD

**Issue by opicciotto** [couchbase/couchbase-lite-java-core#371] opened 2015-01-08 15:05 UTC
I have an Android Phonegap, application using CBlite based on version  1.0.0-beta3rc10 (uses the couchbase-lite-java-core-1.0.0-beta3rc10.jar) working perfectly with replication with a CouchDB server 1.6.1. I am replicating from the server about 6000 documents to the mobile starting from an empty database (Not even created ) on the mobile .

By looking to the CouchDB server console I can see all the requests the client is doing to the server, As I can see, after issuing a long poll, the client tries to download each document from the server,  at regular intervals, the client issues a PUT request.

Using latest (GIT release/1.0.3.1) Version, I experience a weird behavior starting from an empty database on the client side.:

1) Long poll is done, and documents start to be downloaded.
2) No PUTs are done at regular intervals..
3) Downloading stops (Seems stalled) before having done all the 6000 documents..
4) The only way to restart downloads is by killing the mobile app and restarting it and in this case, downloads seems to start again at the beginning
5) After several mobile apps restarts, the 6000 documents are correctly downloaded...

You can find a netcapture done with Wireshark Here :
http://filebin.ca/1nRvbwb3GBWw/Couchbaselite1.03replication.zip

Unzip to get the .pncapng file

**Comment by tleyden** [comment] 2015-01-08 15:15
For uploading the network capture traffic, you could look at http://filebin.ca/

**Comment by tleyden** [comment] 2015-01-08 15:20
Also it would be very helpful if you could test with the master branch as well.  Are you using maven artifacts, the zipfile, or directly depending on the source?

**Comment by opicciotto** [comment] 2015-01-08 15:22
I am using the source directly, and yes I will test the the master branch

**Comment by tleyden** [comment] 2015-01-08 21:14
Thanks.  Let us know how that goes, and then we'll look into reproducing it / diagnosing it.

**Comment by hideki** [comment] 2015-02-16 20:38
Hi @opicciotto 

I tried to reproduce this issue with following condition, however I can not reproduce it.

App: I wrote the [simple test app](https://github.com/hideki/couchbase-lite/tree/master/test/SimpleCouchDBClient) to reproduce this issue. My test app is Android app using 
CBL for Android v1.0.4 (PhoneGap internally uses CBL Android). Replicator is one shot (not continuous)

CouchDB: CouchDB v1.6.1 for OSX

Results: Pull replication could download 6000 documents without hanged/stopped.

Note: I also tried to downloads more than 10K docs, but it also works fine.


Can you try to use 1.0.4?

I will close this ticket because of not reproducible. But I you still encounter this, please reopen the ticket.

**Closed by hideki** 2015-02-16 20:38 UTC
Labels: bug, in progress, P1: high, S3: major, size-large, testneeded

**Comment by opicciotto** [comment] 2015-02-17 06:08
Ok Hideki, the problem was occurring with continuous replication with the PhoneGap Plugin available on cordova.io. When we tested with the master branch it was ok, I assume that the issue has been fixed since ...

It would be a good idea to update the plugin in Cordova.io  (Still in 1.03...)

**Comment by hideki** [comment] 2015-02-17 06:12
@opicciotto Thank you for your update.

We are working for CBL for PhoneGap v1.0.4 release. But it is not ready yet.

@pasin Once v1.0.4 is ready, please let @opicciotto know.
