### ISSUE TITLE
Performance: Pull replication slow

### ISSUE THREAD

**Issue by DayronIG** [couchbase/couchbase-lite-java-core#814] opened 2015-11-11 04:47 UTC
I have a problem , the replication pull in android is very slow , i have 20000 documents.
The connection to internet is very good. and the replication in IOS client is very most fast.

Android client initial replication is very slow, take about 3 hours.

**Comment by hideki** [comment] 2015-11-11 06:45
What version of Couchbase Lite Android are you using? v1.1.0?

**Comment by DayronIG** [comment] 2015-11-11 17:39
Yes i use last version v.1.1.0,  and this version is very slow. 
Is there any solution to this slowly so huge?

**Comment by hideki** [comment] 2015-11-11 17:51
Replication slowness on Android is usually caused by memory usage during replication. It depends on number of documents, its number of revisions, document size, number of attachments, and attachment size.

Could you please provide sample document with attachment if doc has attachment?

Thanks!

**Comment by DayronIG** [comment] 2015-11-11 18:02
I have a high number of revisions, the documents are continually changing , there is a technique for the purification of reviews, and the volume of documents is 2000 , and it takes around 2 hours,

**Comment by hideki** [comment] 2015-11-13 22:52
Log messages during replication might give us insight. Could you please add following  codes before initializing Manager to enable VERBOSE level log message, and provide log messages?
```
            Manager.enableLogging(TAG, Log.VERBOSE);
            Manager.enableLogging(Log.TAG, Log.VERBOSE);
            Manager.enableLogging(Log.TAG_SYNC_ASYNC_TASK, Log.VERBOSE);
            Manager.enableLogging(Log.TAG_SYNC, Log.VERBOSE);
            Manager.enableLogging(Log.TAG_BATCHER, Log.VERBOSE);
            Manager.enableLogging(Log.TAG_CHANGE_TRACKER, Log.VERBOSE);
            Manager.enableLogging(Log.TAG_REMOTE_REQUEST, Log.VERBOSE);
            Manager.enableLogging(Log.TAG_DATABASE, Log.VERBOSE);
```
Thanks!

**Comment by hideki** [comment] 2015-12-12 00:40
Related: https://github.com/couchbase/couchbase-lite-android/issues/686

**Comment by pasin** [comment] 2016-01-08 23:43
Test Data:
- 100000 documents
- Each document has 10K size
- 6000 documents has two 100k attachments

CBL Android, Master [892610ac](https://github.com/couchbase/couchbase-lite-android/tree/892610ac1a004f05dd42f4175eb0657de7a6eccf) with [34df7e2f6] (https://github.com/couchbase/couchbase-lite-java-core/commit/34df7e2f67031e3cdfb58e3f260e0893acd5b4af) patch, Nexus 5x : 1717 seconds (no crash)

CBL iOS 1.2, iPhone 6 : 882 seconds

**Comment by hideki** [comment] 2016-10-03 21:56
Duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/1410
I will close this ticket

**Closed** 2016-10-03 21:56 UTC
Labels: bug, reproduce/investigate
